### ISSUE TITLE
Aggiornare gli esempi e le linee guida con i dati AFAM

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#100]

**Comment by davidelongo-ey** [comment]
non mi ritrovo i dati AFAM, @denismarini  riesci a girarmeli cosi analizzo?

**Comment by denismarini** [comment]
Te lo allego qui

[_per Denis Esempi - risposte 2.docx](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/files/13981416/_per.Denis.Esempi.-.risposte.2.docx)

**Comment by davidelongo-ey** [comment]
Ho aggiornato gli esempi di IFS01 sia json sia yaml.
è stato aggiunto un nuovo campo chiamato learinig_cfa (per gli AFAM) analogamente a quanto fatto per il learning_ssa
sono state aggiornate le LG
