### ISSUE TITLE
[IFS02.1] Nella request il codice fiscale e la key sono opzionali e non obbligatorie inoltre andrebbero descritte meglio le obbligatorietà nelle linee guida

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#101]
- [x] Eliminare le obbligatorietà
- [x] Rivedere l'esempio con uno coerente
- [ ] Rivedere le linee guida IFS02 e IFS06

![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/ee0af348-5073-488e-b057-d168136d6dd3)

![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/2d6eb4c3-b8a5-4ff4-8ded-7d20681d5f08)

**Comment by davidelongo-ey** [comment]
Eliminare le obbligatorietà (**Fatto**)
 
![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139359776/9d611759-6d3c-48bc-bcc6-542437a77e94)

 Rivedere l'esempio con uno coerente (**Fatto** vedi issue #111 )
 
 Rivedere le linee guida IFS02 e IFS06 (da rivedere)

**Comment by denismarini** [comment]
@davidelongo-ey chiudo questa e manteniamo la #111
