### ISSUE TITLE
[IFS02] - Warning sul numero massimo e minimo dell'array come riportato nella figura di dettaglio

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#102]
![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/d01f883c-bbcc-4f29-9b55-9620d2be3dea)

**Comment by davidelongo-ey** [comment]
Sul branch dev non riscontro problemi di warning.
che versione del file stavi verificando? anche il checker non mi evidenzia nessuna problematica.

fammi sapere

**Comment by denismarini** [comment]
@denismarini ho fatto nuovamente la prova con il sorgente del branch deve è ottengo medesimo warning come nell'immagine. Utilizzo l'editor swagger

<img width="1350" alt="image" src="https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/5a50b4c3-0ea7-4b43-8a4a-5c9d59942217">

**Comment by davidelongo-ey** [comment]
ok risolto.
il warning lo mostra solamente la versione alpha del portale https://editor-next.swagger.io/

**Comment by denismarini** [comment]
La chiudo dopo aver verificato che è risolta, grazie @davidelongo-ey
