### ISSUE TITLE
[IFS02.1] attributo x-stoplight come nell'immagine di dettaglio, lo possiamo eliminare?

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#103]
Possiamo anche eliminarlo su tutte le API?

![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/dc0ce479-4b1a-43d8-ad65-fe661662ed48)

**Comment by davidelongo-ey** [comment]
attributo eliminato da tutti gli yaml.
pushato su branch dev

**Comment by denismarini** [comment]
@davidelongo-ey per favore non chiudere le issue ma portale in stato di done e assegnale a me

**Comment by denismarini** [comment]
Verificato, la chiudo
