### ISSUE TITLE
[IFS01.1] Parametro cursor nell'esempio

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#104]
- [x] un esempio senza mettere il parametro cursor, eliminare null
- [x] secondo esempio con il parametro cursor valorizzato, per la seconda richiesta
- [x] Migliorare i nomi degli esempi sulla combo (es.: prima invocazione, invocazioni successive alla prima)

Da migliorare anche tutte le altre api con il parametro "cursor" e mettere in risalto questo nelle linee guida

![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/2df5d7ef-d683-4365-905a-3e5c098f9ef3)

**Comment by davidelongo-ey** [comment]
Ho preddisposto anche una descrizione direttamente nello swagger

**IFS01:**
![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139359776/cdd72302-4ce0-4895-883a-60491e5543a3)

**IFS06 + IFS07:**
![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139359776/9c58bdcd-bcb2-4c1c-a1cc-7f66f795cdfb)
