### ISSUE TITLE
[IFS02.1] Eliminare gli attributi x-jsonld che introdurremo quando facciamo il merge con dev-onto

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#105]
- [ ] 1. Eliminare l'obbligatorietà "generale" dagli oggetti Person-data e Enrollments come nell'immagine allegata
- [x] 2. Eliminare gli attributi x-jsonld che introdurremo quando facciamo il merge con dev-onto
- [ ] 3. Aggiustare tutte le obbligatorietà della risposta come concordato e sulla base del decreto ANIS
- [ ] 4. Aggiornare le linee guida con tutte le regole di obbligatorietà della request e della response

Collegata alla #97 

![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/7e7f462d-193a-442a-aa23-559fbb672b20)

**Comment by davidelongo-ey** [comment]
per il punto 3 intendi quanto presente nella issue [#97](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/issues/97) ?

Se si: sono regole di obbligatorietà che dobbiamo/possiamo mettere nelle linee guida e non è possibile definire tutte le logiche in un openapi.yaml

Fammi sapere

**Comment by denismarini** [comment]
@davidelongo-ey hai ragione tu, il punto 1 e il punto 3 è un mio errore quindi non le facciamo. 
Per il punto 4 manteniamo solo la #97 

In questa invece chiudiamo solo il punto 2 di seguito
- [ ] 2. Eliminare gli attributi x-jsonld che introdurremo quando facciamo il merge con dev-onto

**Comment by davidelongo-ey** [comment]
ho eliminato tutti gli attributi x-jsonld da tutti i file yaml (punto 2)

**Comment by denismarini** [comment]
Verificato correttamente, la chiudo, grazie @davidelongo-ey
