### ISSUE TITLE
[IFS01] Errore nell'esecuzione dell'esempio

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#106]
L'errore è mostrato nella seguente immagine

![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/4ae1e826-9e8d-4d3a-8e60-263169008ab8)

**Comment by davidelongo-ey** [comment]
l'abiitazione dei CORS dipende dal server su cui verrà ospitata/deployata l'applicazione.
Gli yaml sono solamente template e in aggiunta non possono implementare logiche di CORS.

Quanto segnalato non è un BUG, chiudo

**Comment by denismarini** [comment]
@davidelongo-ey sai perché in alcuni casi abbiamo l'errore e in altri no?

**Comment by davidelongo-ey** [comment]
il problema dei CORS si verifica per tutte le api e metodi nel momento in cui viene fatta l'esecuzione della chiamata "mockata" (tramite il tasto Execute)

**Comment by denismarini** [comment]
Grazie @davidelongo-ey , verificata, la chiudo
