### ISSUE TITLE
[IFS01.1] Payload della response non corretto, vedere il dettaglio

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#107]
Da cambiare come indicato di seguito in grassetto nei seguenti posti

- [x] src/IFS01-offerta-formativa.yaml 
- [x] doc/03_analysis/io_schema/IFS01.1-response.json

"degree_courses": [
    {
      "programme_type_code": "C6",
      **"programme_access": "Libero", --> fare l'esempio in inglese (lo possiamo enumerare?)**
      "course_location": "Milano Bovisa",
      "course_area": "Ingegneria industriale",
      "degree_class_code": "L-9",
      **"degree_class_language": "IT", --> degree_course_language
      "degree_class_period_years": 3, --> degree_course_period_years**
      "degree_course_code": "353",
      "total_credits": 180,
      "academic_year": "2023/2024"
    },

**Comment by davidelongo-ey** [comment]
già fixato in fase di risoluzione issue #109

**Comment by davidelongo-ey** [comment]
ho aggiunto l'enum per l'attributo programme_access:

       programme_access:
          type: string
          description: Access to the course / Accesso al corso
          example: free access
          readOnly: true
          minLength: 1
          maxLength: 99
          **enum:
            - free access
            - limited number access**


come esempio per ora ho inserito solo 2 valori

**Comment by denismarini** [comment]
Verificata che è stata risolta, la chiudo, grazie @davidelongo-ey
