### ISSUE TITLE
[IFS01.2] Correzione delle obbligatorietà

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#108]
- [ ] IFS01.2 Eliminare nella request l'obbligatorietà del codice classe

![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/5abe2c80-5a00-4ce7-98f8-64a1e2843e9e)

**Comment by davidelongo-ey** [comment]
fatto

**Comment by denismarini** [comment]
![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/25a29bb7-7d38-444e-a1c0-37ceb4851f22)

**Comment by davidelongo-ey** [comment]
Fatto

**Comment by denismarini** [comment]
Verificata, la chiudo
