### ISSUE TITLE
[IFS01.2] Correzione della response

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#109]
- [x] correggere la response come di seguito in **grassetto**

{
  "programme_type_code": "L2",
  "programme_access": "Libero",
  "course_location": "Milano Bovisa",
  "remote_mode": "on-site",
  "course_area": "Ingegneria industriale",
  "degree_class_code": "L-9",
  **"degree_class_language": "IT", -- > degree_course_language
  "degree_class_period_years": 3, --> degree_course_period_years**
  "degree_course_code": "353",
  "total_credits": 180,
  "academic_year": "2023/2024",
  "first_year_activation_course": "2010/2011",
  "website_university": "http://www.ingindinf.polimi.it",
  "website_course": "http://....",
  "curriculum_list": [
    {
      "curriculum_name": "NON DIFFERENZIATO",
      "curriculum_learnings": [
        {
          "degree_course_year": 1,
          "learnings": [
            {
              "learning_ssd": "MAT/03",
              "learning_name": "ANALISI E GEOMETRIA 1",
              "learning_code": "081360",
              "learning_cfu": 10,
              "learning_hour": 48,
              "learning_language": "IT",
              "learning_ref": "http://...."
            },
            {
              "learning_ssd": "CHIM/07",
              "learning_name": "FONDAMENTI DI CHIMICA",
              "learning_code": "081374",
              "learning_cfu": 7,
              "learning_hour": 36,
              "learning_language": "IT",
              "learning_ref": "http://...."
            }
          ]
        },
        {
          "degree_course_year": 2,
          "learnings": [
            {
              "learning_ssd": "ING-IND/14",
              "learning_name": "COSTRUZIONE DI MACCHINE 1",
              "learning_code": "05083782",
              "learning_cfu": 10,
              "learning_hour": 40,
              "learning_language": "IT",
              "learning_ref": "http://...."
            },
            {
              "learning_ssd": "ING-IND/13",
              "learning_name": "MECCANICA APPLICATA ALLE MACCHINE",
              "learning_code": "54828",
              "learning_cfu": 10,
              "learning_hour": 48,
              "learning_language": "IT",
              "learning_ref": "http://...."
            }
          ]
        }
      ]
    },

**Comment by davidelongo-ey** [comment]
modificati esempi response e definizione IFS01.yaml

**Comment by denismarini** [comment]
Verificata, la chiudo
