### ISSUE TITLE
[IFS02.1] Rimuovere esempi refusi sulle API

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#110]
- [ ] Rimuovere gli esempi refusi come in figura

![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/ba6bcfc8-af17-4ff6-8434-c0d979915b1c)

**Comment by davidelongo-ey** [comment]
non sono esempi refusi, sono le varie casistiche di request possibili da inviare in post.
"Example 1 Enrollments" e "Example 2 Enrollments" differiscono per il campo degree_class_code valorizzato o nullo (era una casistica che ci avevi detto di impostare tra gli esempi.

Fammi sapere cosa/come preferisci fare

**Comment by denismarini** [comment]
@davidelongo-ey  ho aggiornato con un nome degli esempi più esplicito come nell'immagine



![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/faed3fa0-8b3d-410b-9f39-fdeb438ca9e8)

**Comment by davidelongo-ey** [comment]
ok visto

**Comment by denismarini** [comment]
Verificata, la chiudo
