### ISSUE TITLE
[IFS02] Rendere reale l'esempio di tutte le API json e yaml

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#111]
- [ ] Eliminare institute code come nel seguente modo perché è il caso più comune, oppure fare due esempi con e senza l'institute_code, da correggere su tutte da IFS02.2 a IFS02.X

{
  "tax_code": "RSSMRA80A01F205D",
  "person_id": "12345678A",
}

**Comment by davidelongo-ey** [comment]
creati esempi cosi formattati:


/*ESEMPIO 1*/

{
  "tax_code": "RSSMRA80A01F205D",
  "person_id": "12345678A"
}

/*ESEMPIO 2*/
{
  "tax_code": "RSSMRA80A01F205D",
  "person_id": "12345678A",
  "institute_code": "AA" /*Facoltativo*/
}

**Comment by denismarini** [comment]
@davidelongo-ey di seguito: 
- [ ] Dovremmo modificare anche la IFS02.1 in questo caso dobbiamo gestire gli esempi con key e senza key che  sono i più comuni
- [ ] dovremmo  modificare tutti gli esempi su tutti i .yaml

**Comment by davidelongo-ey** [comment]
per IFS2.1 ho modificato gli esempi nello yaml e il json

**Comment by denismarini** [comment]
@davidelongo-ey gli esempi riportati non vanno bene come in figura, dovremmo riportare esempi reali come di seguito
<img width="539" alt="image" src="https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/c8008a1f-5762-4489-bc3a-91914abe68f5">

1. Example with CF/personID
2. Example with key

L'istituto lo spieghiamo nelle linee guida che lo userà ANIS per interagire con ANS e per gli IFS non è obbligatorio

Se hai dubbi ne parliamo a voce

**Comment by davidelongo-ey** [comment]
Gli esempi 1 e 2 sono stati modificati

**Comment by denismarini** [comment]
Verificato, la chiudo
