### ISSUE TITLE
[IFSX] lo schema sulla invocazione non fornisce la struttura dello oggetto request ma solo la descrizione

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#113]
Qui quello che vedo nelle API Università

![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/8f202e28-3ae4-4968-b55d-f10d226f45d4)

Nella seguent immagine quello che vedo nell'esempio di default di swagger editor 

![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/585ff96b-7513-4c21-b2a2-eaa8bf9e6acc)

**Comment by denismarini** [comment]
@davidelongo-ey dobbiamo anche capire se restituire il cursor quando è nullo

**Comment by davidelongo-ey** [comment]
ho fatto in modo che ovunque le request si vedano cosi

![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139359776/8a0cc94e-e45e-4e45-bd43-0f09756a01fe)


Per IFS01 : al cursor  ho aggiunto la proprietà "nullable: true" (cosi facendo possono restituire anche un curson=null )

**Comment by denismarini** [comment]
Verificata, la chiuda
