### ISSUE TITLE
[IFSX] Eliminare la proprietà read-only negli schemi delle request in post

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#115]

**Comment by davidelongo-ey** [comment]
Fatto su branch dev

**Comment by denismarini** [comment]
@davidelongo-ey perché non li abbiamo tolti tutti? 


![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/f1692049-a3e9-428e-b443-98de11e37d42)

**Comment by davidelongo-ey** [comment]
avevamo detto di elilminarli solo negli oggetti presenti/proprietà della Request.
procedo alla rimozione

**Comment by davidelongo-ey** [comment]
Fatto

**Comment by denismarini** [comment]
Verificato, la chiudo
