### ISSUE TITLE
[LG] Aggiungere nelle linee guida il riferimento al masterdata

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#118]
[File masterdata](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/547bc1cffb4a99aaa4f11f13a7ff59ddeae27695/doc/03_analysis/masterdata/masterdata.xlsx)

**Comment by davidelongo-ey** [comment]
fatto

**Comment by denismarini** [comment]
Aggiornata la sezione sulle linee guida. Da aggiornare le LG appena è definitivo lo schema del "Master data", lascio la issue aperta in stato "in progress"
