### ISSUE TITLE
[IFS06][IFS07] Aggiungere esempi senza cursor per l'ultima invocazione

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#120]
Su IFS06.1 e IFS07.1, a mio parere manca l’esempio nel quale l’istituto non avendo più niente da inviare, invia il cursore vuoto o nullo

**Comment by davidelongo-ey** [comment]
abbiamo messo queste note nello yaml/swagger

![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139359776/070f2ff6-8016-4738-9dce-1d07f9902d50)

potrei fare un esempio di response che non contiene il cursor valorizzato, che ne pensi?

**Comment by denismarini** [comment]
@davidelongo-ey sono d'accordo con l'esempio da te proposto, non restituiamo il cursor

**Comment by davidelongo-ey** [comment]
modifica eseguita

![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139359776/4147a306-cca8-44d1-a541-121f0553c80d)

**Comment by denismarini** [comment]
aggiornata, la chiudo
