### ISSUE TITLE
[IFS01] correggere l'attributo learning_ssd in learning_ssd_sad

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#121]
Aggiungere l'attributo learning_ssa affianco a learning_ssd 

learning_ssd (Settore Scientifico Disciplinare)
learning_ssa (Settore Artistico Disciplinare)

**Comment by denismarini** [comment]
Verificata, la chiudo

**Comment by isidata23** [comment]
in effetti learning_ssa affianco a learning_ssd dovrebbe essere learning_sad affianco a learning_ssd in quanto SAD=Settore Artistico Disciplinare e SSD = Settore Scientifico Disciplinare
