### ISSUE TITLE
[IFS03.4] Aggiungere "vote scales" nella struttura "attended_learnings"

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#123]
- [x] Aggiornare yaml
- [x] Aggiornare json io

Da aggiungere:

learning_grading_scale 
learning_grading_scale_min 
learning_grading_scale_max

Ricordarsi di mettere in verde il business canvas sulla tab it_evidences

**Comment by davidelongo-ey** [comment]
fatto, modificato YAML+JSON+Canvas

**Comment by denismarini** [comment]
Verificato, la chiudo
