### ISSUE TITLE
[IFS0X.Y] Aggiungere nei tag dello YAML il prefesso IFS0X.Y -

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#127]
Esempio:

![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/a8b8fdd4-10ce-43f1-9050-17a2faf2134f)

**Comment by davidelongo-ey** [comment]
fatto

**Comment by denismarini** [comment]
Verificato, la chiudo
