### ISSUE TITLE
[IFS07] Diversificare le chiavi hash (key) nell'esempio

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#129]
`                     qualifications_hash:
                        - key: '8e44f796d7478a135c226598939d56a5b0d9405210235d4845ed158a7fec7535'
                          hash: '56c3880bfcc4df0e35780c805d9ec942bbb8b4e237c1b63c6f2688cb58ef0a3a'
                        - key: '8e44f796d7478a135c226598939d56a5b0d9405210235d4845ed158a7fec7535'
                          hash: '56c3880bfcc4df0e35780c80sdlkjljiirpepw85830t3j85jg0fj054fj04jf03'
                        - key: '8e44f796d7478a135c226598939d56a5b0d9405210235d4845ed158a7fec7535'
                          hash: 'df8340f834tr8f3j84fj48jf83fngooero45305jf30l04k0r43kfd043kdew34t'`

cc @fabio2602

**Comment by davidelongo-ey** [comment]
si si già fatto Denis, ho modificato sia il json sia lo yaml

   "enrollments_hash": [
      {
        "key": "8e44f796d7478a135c226598939d56a5b0d9405210235d4845ed158a7fec7535",
        "hash": "56c3880bfcc4df0e35780c805d9ec942bbb8b4e237c1b63c6f2688cb58ef0a3a"
      },
      {
        "key": "p9sndsh75636d7478a135c226598939d56a5b0d94052102oiasdh7632bbc78h843",
        "hash": "56c3880bfcc4df0e35780c80sdlkjljiirpepw85830t3j85jg0fj054fj04jf03"
      },
      {
        "key": "qmane9vsd7cksad8e44f796d7478a135c226598939d56a5b0d94052102gh9msabv9s",
        "hash": "df8340f834tr8f3j84fj48jf83fngooero45305jf30l04k0r43kfd043kdew34t"
      }
    ]

**Comment by denismarini** [comment]
Verificata, la chiudo
