### ISSUE TITLE
[IFS02-IFS03-IFS04-IFS05] Campo birth_place - Definire nelle formato

### ISSUE THREAD

**Issue by davidelongo-ey** [italia/api-padigitale2026-misura1.3.1-uni-afam#132]
Definire nelle LG il formato del campo birth_place che deve contenere:
<nome_comune>, <_provincia>, <_nazione>
Es: birth_place="Milano, MI, Italia"

per città estere, se la provincia non è presente, inserire EE

- Modificare esempi Json e Yaml

**Comment by davidelongo-ey** [comment]
![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139359776/32441e93-0000-4ab6-8752-be2f8de0d86c)

**Comment by davidelongo-ey** [comment]
verificare come creare il pattern tramite RegEx

**Comment by denismarini** [comment]
@davidelongo-ey sarebbe da cambiare la regular expression in questo modo .*,[a-zA-Z]*,[a-zA-Z]* e l'esempio: Italia,Roma,RM attenti a non mettere lo spazio dopo la virgola. Se la città e la provincia non esistono mettono Svizzera,,

**Comment by denismarini** [comment]
Ho aggiunto anche dei TODO nelle linee guida

**Comment by davidelongo-ey** [comment]
Aggiorno con questo Pattern: ^[a-zA-Z ]+,[a-zA-Z ]{2},[a-zA-Z ]+$
(Abilita anche gli "spazi" nelle stringhe)

Ti faccio sapere come fatto

**Comment by denismarini** [comment]
@davidelongo-ey in questo modo la provincia diventa obbligatoria così come anche il comune, sarebbe meglio qualcosa di più libero vista anche la natura straniera 

.*,[a-zA-Z],[a-zA-Z]* 

devono essere possibili anche pattern come Cuba,, oppure Italia,RM,frascati oppure Italia,,frascati la stringa che mi hai proposto non copre questi casi

Che ne pensi?

**Comment by davidelongo-ey** [comment]
per me OK
Ho ri-validato tutti gli YAML con la nuova RegEx ed è tutto OK (IFS02/3/4/5)

Secondo me si può chiudere questa issue
