### ISSUE TITLE
[IFS04-IFS05] Formato timestemp

### ISSUE THREAD

**Issue by ldoneda** [italia/api-padigitale2026-misura1.3.1-uni-afam#133]
Problema nel formato richiesto per timestemp. 
Abbiamo provato ad inserire il timestemp nel formato richiesto ma abbiamo un problema segnalato dal checker.
![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139358239/43635ef7-9d4f-4d17-8e87-f7838f80727b)
Il formato richiesto per la modifica non è coerente con quello definito nell'attributo.
![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139358239/3e828e99-1fab-45cd-8738-f7c271e63ef0)
Il formato correttto da utilizzare è quello già inserito. Se si vuole utilizzare quello richiesto bisogna togliere il formato nella definizione dell'attributo.

**Comment by denismarini** [comment]
Ciao @ldoneda,

Possiamo cambiare il numero dell'attributo da data_request_timestamp in data_request e formalizzare il valore richiesto con il tipo data e non timestamp
