### ISSUE TITLE
[IFS03.3] Da aggiornare da analisi con ISIDATA

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#136]
Da correggere come mostrato in figura:

- course --> learning
- aggiungere learning name
- da rimuovere received
- has_parent_relation --> null (da cambiare tutti gli esempi)

Aggiornare YAML e JSON

**AS-IS**
![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/051400c0-38d1-473e-9aa8-bac24c6fd74d)

**TO-BE**
![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/4523179b-dd84-4eee-b5bc-59accee5c4e9)

**Comment by ldoneda** [comment]
come esempio per learning name utilizziamo xxxxx, yyyyy, zzzz come nella foto o utilizziamo nome di esami reali?

**Comment by denismarini** [comment]
@ldoneda proviamo a mettere degli insegnamenti reali, ne ho parlato con @davidelongo-ey

**Comment by denismarini** [comment]
Ottimo, la chiudo!
