### ISSUE TITLE
Piccolo refuso

### ISSUE THREAD

**Issue by s-cenni** [italia/api-padigitale2026-misura1.3.1-uni-afam#138]
In questa sezione: https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam?tab=readme-ov-file#globe_with_meridians-ifs012---educational-offering-detail c'è un piccolo refuso

"Nella response per le università compilare i campi learning_ssd e **learinig**_cfu"

**Comment by s-cenni** [comment]
Altri refusi: 
https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam?tab=readme-ov-file#globe_with_meridians-ifs021---academic-enrollments

rimandare all'**erorre** 404 (vedi esempio nel file YAML)

ad **escluisone** **del attirubuto** degree_class_code

https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam?tab=readme-ov-file#globe_with_meridians-ifs031---academic-qualifications

rimandare all'**erorre** 404 _(refuso replicato)_

ad **escluisone del attirubuto** degree_class_code

**Comment by denismarini** [comment]
> In questa sezione: https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam?tab=readme-ov-file#globe_with_meridians-ifs012---educational-offering-detail c'è un piccolo refuso
> 
> "Nella response per le università compilare i campi learning_ssd e **learinig**_cfu"

@s-cenni quello che è scritto nelle LG sembra essere corretto ossia, si valorizza ssd (settore scientifico disciplinare) e cfu (crediti formativi) per gli atenei/università mentre si valorizza ssa(settore artistico disciplinare) e cfa (crediti formaitvi) per gli istituti AFAM, altrimenti ti chiedo di fornire maggiori dettagli sul refuso, 

Mille grazie

**Comment by denismarini** [comment]
> rimandare all'**erorre** 404 (vedi esempio nel file YAML)
> 
> ad **escluisone** **del attirubuto** degree_class_code

@s-cenni ti chiedo per favore di argomentare meglio la segnalazione perché non ci è chiara,

Mille grazie

**Comment by s-cenni** [comment]
> > rimandare all'**erorre** 404 (vedi esempio nel file YAML)
> > ad **escluisone** **del attirubuto** degree_class_code
> 
> @s-cenni ti chiedo per favore di argomentare meglio la segnalazione perché non ci è chiara,
> 
> Mille grazie
@denismarini la mia segnalazione era solo relativa a errori di battitura e non sul contenuto.
Ho scritto in grassetto le parole che contenevano degli errori di battitura che avevo notato in una prima rapida lettura. Nel primo caso "learinig_cfu" è già stato corretto in "learning_cfu" ma ci sono ancora alcuni errori ripetuti (ad esempio "erorre 404" è presente 5 volte con lo stesso refuso)

**Comment by denismarini** [comment]
@s-cenni ora è tutto chiaro e abbiamo corretto secondo tue indicazioni, mille grazie per il contributo

Buon fine settimana
