### ISSUE TITLE
[IFSX] Da eliminare institute_code su tutti i metodi SDG

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#140]
@davidelongo-ey  le json in shcema_io le ho modificate io, prima di aggiornare gli yaml dateci un'occhiata al mio intervento sul commit

**Comment by davidelongo-ey** [comment]
Ciao Denis,
Ho modificato IFS02 e 03 sia YAML sia JSON
