### ISSUE TITLE
eservice IFS03 | qualification_name

### ISSUE THREAD

**Issue by LeaLenoci** [italia/api-padigitale2026-misura1.3.1-uni-afam#146]
Si richiede di rendere **opzionale** l’attributo **qualification_name** presente nell’eservice IFS03 (titoli accademici)

**Comment by denismarini** [comment]
@LeaLenoci @fabio2602 abbiamo apportato la vostra richiesta di cambiamento alla specifica

[release-note](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/711b382f8bae2dc20d598b416d6e85f2efc98412/release-note.md)

**Comment by denismarini** [comment]
Chiudo io la issue, visto che è passata una settimana, se non riscontrate correttamente l'intervento potete riaprirla
