### ISSUE TITLE
corsi-istituto.yaml

### ISSUE THREAD

**Issue by rockmesh** [italia/api-padigitale2026-misura1.3.1-uni-afam#15]
Corsi istituto dovrebbe restituire anche la facoltà per capire se un corso è (ad es.) di Giurisprudenza o Economia....

**Comment by AulicinoDiego** [comment]
ok aggiungiamo la proprietà "faculty" per ogni corso

**Comment by AulicinoDiego** [comment]
https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/pull/16#issue-1776974091
