### ISSUE TITLE
Possibile errore su IFS02.1 tag 2.0.3

### ISSUE THREAD

**Issue by fabio2602** [italia/api-padigitale2026-misura1.3.1-uni-afam#156]
Nell' eservice IFS02.1 sull'attributo degree_course_year è presente questa regular expression "^\d{2}$", la quale ammette che sull'attributo siano presenti esattamente 2 numeri.

A mio parere è più corretta la regex "^\d{1,2}$" dove sono ammessi la massimo due digit.

Saluti

**Comment by davidelongo-ey** [comment]
Si corretto, abbiamo modificato lo YAML
Grazie per la segnalazione, a presto
