### ISSUE TITLE
IFS01-offerta-formativa:  come indicare che un insegnamento non ha un anno di corso definito?

### ISSUE THREAD

**Issue by vpxyz** [italia/api-padigitale2026-misura1.3.1-uni-afam#159]
Salve, 
la specifica IFS01 definisce degree_course_year come un intero copreso tra 1 e 99. 
Noi però abbiamo diverse offerte formative con insegnamenti per i quali non è definito in quale anno lo studente lo deve/può seguire, può essere seguito in uno qualsiasi degli anni di corso. 
Come possiamo indicare questa caratteristiche delle nostre offerte formative?
Grazie

**Comment by NETTunoPA** [comment]
Buongiorno, 
anche noi abbiamo la stessa problematica. Ci possono essere discipline che possono essere seguite dal primo al terzo anno, le ripetiamo in ogni occorenza dell'elemento "learnings" relativo agli anni?

**Comment by denismarini** [comment]
Buongiorno @vpxyz e @NETTunoPA mi scuso per il ritardo con il quale stiamo rispondendo, ho capito la problematica e mi confronto internamente al gruppo di lavoro per rispondervi tra oggi e domani. 

A presto!

**Comment by denismarini** [comment]
Salve @vpxyz e @NETTunoPA, a fronte di un confronto interno al gruppo di lavoro costituito per l'avviso 1.3.1 è stato deciso che per il dettaglio dell'offerta formativa  è sufficiente fornire solo il primo anno di corso dell’offerta formativa disponibile per la coorte identificata.
Ricordo che questi dati sono a scopo orientativo dello studente e quindi sono dati che dovrebbero alimentare un manifesto (es. utilizzabile da Universitaly)e non una programmazione (che sarà fornita dallo specifico portale dell'università), quindi la loro organizzazione dipende dallo scopo appena citato e l'istituto è libero di organizzare i dati anche in coordinazione con il MUR per Universitaly.

Stiamo aggiornando la documentazione delle API con queste informazioni.

Grazie
