### ISSUE TITLE
[IFS01.2] Anno accademico offerta formativa

### ISSUE THREAD

**Issue by NETTunoPA** [italia/api-padigitale2026-misura1.3.1-uni-afam#161]
Buongiorno, 
potenzialmente l'offerta formativa cambia di anno in anno di fatti nel servizio "educational-offering-list" viene passato nella request l'anno accademico, perchè questo non avviene anche per il servizio "educational-offering-detail"? Sarebbe comodo almeno averlo come parametro opzionale.
Grazie.

**Comment by denismarini** [comment]
Buongiorno @NETTunoPA,

Abbiamo preso incarico la vostra richiesta, ci confrontiamo nel gruppo di lavoro e vi aggiorniamo qui

Mille grazie per la segnalazione!

**Comment by denismarini** [comment]
Salve @NETTunoPA di seguito quello che è stato deciso dal GdL

degree_course_code
E’ il codice identificativo presente nei dataset “Corsi” pubblicati dal MUR su https://github.com/MIPA-CINECA/codifiche-
mur. In particolare:
- per gli atenei il degree_course_code individua in modo univoco la combinazione: Corso, Classe, anno accademico
della coorte, sede (DEGREE_COURSE_NAME; DEGREE_CLASS_CODE; VALIDITY_YEAR; COURSE_LOCATION);
- per AFAM il degree_course_code non dipende dall’anno accademico.

Saluti,
