### ISSUE TITLE
Corso Mancante

### ISSUE THREAD

**Issue by isidata23** [italia/api-padigitale2026-misura1.3.1-uni-afam#162]
Buon giorno,
abbiamo notato che manca il corso
SCUOLA DI ARMONICA A BOCCA CROMATICA- DCPL 73

in generale vorremmo chiedere, qualora una Istituzione attivi un nuovo corso, a chi dovrebbe rivolgersi per far aggiornare il dataset relativo.

Isidata

**Comment by denismarini** [comment]
Salve @isidata23 

Ho aperto la issue sul repository MIPA-CINECA/codifiche-mur potete raggiungerla anche voi e seguirla, la riporto di seguito

https://github.com/MIPA-CINECA/codifiche-mur/issues/1#issue-2252609934

**Comment by denismarini** [comment]
Salve @isidata23,

Il CINECA ha risolto questa issue sul repository https://github.com/MIPA-CINECA/codifiche-mur/issues/1#issue-2252609934

Grazie
