### ISSUE TITLE
IFS04.2 - Differenza tra esempio e schema

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#163]
Buonasera,
nell'esempio: https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/34cb11e3d07bfb29cf8dc78acf4b73c331f6cc83/doc/03_analysis/io_schema/IFS04.2-response.json è indicato che la response è diversa a seconda se file_code sia valorizzato oppure no nella request; tuttavia, nello schema https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS04-rettifica-iscrizioni.yaml il file_code della request è indicato come obbligatorio.

Come dobbiamo considerare file_code? Facoltativo come nell'esempio oppure obbligatorio come nello schema?

Grazie.

**Comment by denismarini** [comment]
Buongiorno @AlessandroGualdaniUniGe,

Confermo che il **file_code è facoltativo nel caso della IFS04.2 e IFS05.2**, stiamo apportando le correzioni sui branch dev e main. Potrà vedere l'aggiornamento sulla release-note in giornata. Poi faremo anche un tag nelle prossime settimane,

Grazie!
