### ISSUE TITLE
Dataset corsi Università incompleto

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#164]
Buonasera,
nel dataset https://github.com/MIPA-CINECA/codifiche-mur/blob/main/Universita/csv/corsi.csv per l'Università degli Studi di Genova (INSTITUTE_CODE='11') non sembrano esserci tutte le occorrenze dei corsi di studio.

Esempio 1. Per VALIDITY_YEAR=2023 e DEGREE_COURSE_NAME='Informatica' risulta solo:

238155	11	100106203100002 	2031	10025	2023	MT	Informatica

mentre invece dovrebbero esserci anche:

i DEGREE_COURSE_CODE: 244206 e 244207 (relativi rispettivamente al Curriculum Propedeutico e Curriculum Tecnologico).

Esempio 2. Per VALIDITY_YEAR=2023 e DEGREE_COURSE_NAME='Computer Science' risultano solo:

241788	11	100107301900001	3019	10025	2023	MS	Computer Science DATA SCIENCE & ENGINEERING - Artificial intelligence
241790	11	100107301900001	3019	10025	2023	MS	Computer Science DATA SCIENCE & ENGINEERING - Data analytics
241791	11	100107301900001	3019	10025	2023	MS	Computer Science SOFTWARE SECURITY & ENGINEERING - Software security
241806	11	100107301900001	3019	10025	2023	MS	Computer Science SOFTWARE SECURITY & ENGINEERING - Software engineering

ma manca il curriculum: Data Science & Engineering - Visual Computing (DEGREE_COURSE_CODE=241789) oltre al corso generico (DEGREE_COURSE_CODE=238197).

Grazie.

**Comment by denismarini** [comment]
Gent.mo @AlessandroGualdaniUniGe,

Ho aperto la sua segnalazione sul repository https://github.com/MIPA-CINECA/codifiche-mur/issues/2 inoltre segnaliamo questa issue al gruppo di lavoro.

Mille grazie per la segnalazione!

**Comment by denismarini** [comment]
Buongiorno @AlessandroGualdaniUniGe,

Ti comunico che è stata risolta questa issue sul repository MIPA-CINECA/ https://github.com/MIPA-CINECA/codifiche-mur/issues/2

Grazie,
