### ISSUE TITLE
Differenza tra esempio e schema IFS05.1

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#166]
Buongiorno,
abbiamo notato una differenza tra l'esempio di response di IFS05.1 e lo schema.

In particolare, nell'esempio: https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/03_analysis/io_schema/IFS05.1-response.json non c'è il campo response_code mentre è indicato come obbligatorio nello schema https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS05-rettifica-titoli.yaml

Il campo response_code è, quindi, obbligatorio come nello schema oppure non deve esserci come nell'esempio?

Grazie.

**Comment by denismarini** [comment]
Ciao @AlessandroGualdaniUniGe confermo che response_code è obbligatorio ed abbiamo corretto gli esempi in formato json.
Mille grazie per la segnalazione!
