### ISSUE TITLE
Differenza tra esempio e schema IFS05.4 (qualifications)

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#169]
Buongiorno,
abbiamo notato una differenza tra l'esempio della request di IFS05.4 https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/03_analysis/io_schema/IFS05.4-request.json in cui è presente il campo qualifications (che è un array) rispetto allo schema https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS05-rettifica-titoli.yaml dove è indicato il campo qualifications come oggetto.

Quale tipo di dato dobbiamo aspettarci nella request relativamente al campo qualifications? Un array (come nell'esempio) oppure un oggetto (come nello schema)?

Grazie.

**Comment by denismarini** [comment]
Ciao @AlessandroGualdaniUniGe ti confermo che si tratta di un array, provvediamo a correggere lo schema.

cc @davidelongo-ey

Mille grazie per la segnalazione!

**Comment by denismarini** [comment]
Buongiorno @AlessandroGualdaniUniGe,

Abbiamo aggiornato la specifica con un array

Mille grazie per la collaborazione
