### ISSUE TITLE
Differenza tra esempio e schema IFS05.4 (data_request)

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#170]
Buongiorno,
abbiamo notato una differenza tra l'esempio della request di IFS05.4 https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/03_analysis/io_schema/IFS05.4-request.json in cui è presente il campo data_request_timestamp (che comprende l'orario) rispetto allo schema https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS05-rettifica-titoli.yaml dove è indicato il campo data_request (in cui non è presente l'orario).

Quale nome di campo dobbiamo prevedere nella request e con che formato? data_request_timestamp (con anche l'orario), come nell'esempio oppure data_request (senza orario) come nello schema?

Grazie.

**Comment by denismarini** [comment]
Buongiorno @AlessandroGualdaniUniGe ,

Abbiamo corretto l'esempio,

Mille grazie per la colaborazione
