### ISSUE TITLE
Differenza tra Linee Guida e Json della response esempio IFS01.1 ed IFS01.2

### ISSUE THREAD

**Issue by isidata23** [italia/api-padigitale2026-misura1.3.1-uni-afam#171]
Buongiorno,
Abbiamo notato una differenza tra l’esempio Json della response per IFS01.1
[api-padigitale2026-misura1.3.1-uni-afam/doc/03_analysis/io_schema/IFS01.1-response.json at main · italia/api-padigitale2026-misura1.3.1-uni-afam (github.com)](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/03_analysis/io_schema/IFS01.1-response.json)
e le line guida
[italia/api-padigitale2026-misura1.3.1-uni-afam: Specifiche API relative alla misura 1.3.1 per l'avviso dedicato alle Università e AFAM (github.com)](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam#ifs01-offerta-formativa)
relativamente al campo "course_location"
In particolare nelle linee guida è indicato come CODICE ISTAT del comune della sede del corso, mentre nell’esempio Json della response viene riportato il nome del comune della sede del corso; in oltre, qualora il corso venga tenuto in più sedi, durate le riunioni del tavolo di lavoro, si era deciso di inserire i vari comuni separati da virgola (Es. Roma, Frascati)
Dobbiamo inserire il Codice o il nome del comune?
In caso di più comuni e di codice i due codici debbono essere separati dalla virgola?

La stessa differenza l’abbiamo notata anche in IFS01.2

**Comment by denismarini** [comment]
Buongiorno @isidata23,

Abbiamo corretto gli esempi come da voi indicato,

Mille grazie per la collaborazione
