### ISSUE TITLE
Url errato

### ISSUE THREAD

**Issue by s-cenni** [italia/api-padigitale2026-misura1.3.1-uni-afam#172]
Il link al file [OpenApi.yaml](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS09-iscrizioni-per-corso.yaml) di questa pagina [IFS09 Iscrizioni per corso](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam?tab=readme-ov-file#ifs09-iscrizioni-per-corso) è errato.

L'errore è dovuto al fatto che alcuni [file di questa pagina](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/tree/main/src) hanno il nome nel formato "IFSXX-" mentre altri "IFSYY_"

**Comment by denismarini** [comment]
Buongiorno @s-cenni,

Risolto!

Mille grazie per la segnalazione
