### ISSUE TITLE
Errori nel file: IFS09_iscrizioni-per-corso.yaml

### ISSUE THREAD

**Issue by s-cenni** [italia/api-padigitale2026-misura1.3.1-uni-afam#173]
1. Nel file [file IFS09-iscrizioni-per-corso.yaml](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS09-iscrizioni-per-corso.yaml#L88C7-L88C37) (riga 88) c'è un refuso: IFS09 è relativo agli iscritti per corso e non per ISEE (che è IFS08).
2. Nella [riga 18](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS09-iscrizioni-per-corso.yaml#L18C4-L18C49) (e poi in altri 2 punti) viene usato _count-accademic-enrollments-by-degree-courses_ ma nella descrizione "Retrieve the number of academic enrollments" la parola academic viene scritta con una "c" sola (che dovrebbe essere la forma corretta). Per coerenza andrebbe scritto sempre nella stesso modo.

**Comment by denismarini** [comment]
Buongiorno @s-cenni,

Ti ringraziamo per la utile segnalazione che abbiamo risolto,
