### ISSUE TITLE
Come ottenere informazioni a partire dal person_id

### ISSUE THREAD

**Issue by calogerocrapanzano** [italia/api-padigitale2026-misura1.3.1-uni-afam#174]
Buongiorno

Visto che potremmo ricevere delle richieste con il solo _person_id_, potete indicarci come ottenere il codice fiscale di una persona a partire dal _person_id_?

Non avendo tale informazione, non sapremmo come rispondere a queste richieste.

Ho provato a verificare se esiste su PDND un servizio ANPR per avere questa informazione, ma non ho trovato nulla di sicuro.

Grazie

**Comment by denismarini** [comment]
Buongiorno @calogerocrapanzano,

Può utilizzare il servizio puntuale sulla PDND C030-servizioAccertamentoIdUnicoNazionale-approvazione_autom erogato dal Ministero dell'interno. Questo servizio è erogato a tutte le PA sulla base del catalogo IPA e le Università e le AFAM pubbliche sono anche esse categorizzate come PA in tale catalogo. Questa sarebbe la soluzione migliore, altrimenti può invocare i servizi esposti dall'anagrafe ANIS ed erogati dal Ministero Università e Ricerca per la verifica di un titolo oppure di un'iscrizione di uno studente e con due obiettivi:

1. Verificare se i dati nell'anagrafe ANIS corrispondono con quelli dell'Istituto
2. Ottenere dalla risposta di questi servizi l'IDANPR (person_id) dello studente

Grazie,

Denis

**Comment by calogerocrapanzano** [comment]
Buongiorno @denismarini 

Grazie per la celere risposta.

Per quanto riguarda la prima soluzione, che era quella che preferirei seguire, ho però un problema.

Leggendo la documentazione del servizio si evince che funziona esattamente al contrario di come ci servirebbe, nel senso che riceve in input il codice fiscale e restituisce il person_id.

A noi serve invece ottenere informazioni a partire da un person_id.

Sbaglio qualcosa io?

Grazie
Calogero

**Comment by denismarini** [comment]
Ciao @calogerocrapanzano,

Hai ragione e ti ringrazio per avercelo fatto notare, ci stiamo confrontando internamente e ti rispondo il più rapidamente possibile. 
Per il momento, se state implementando, considerate obbligatorio il CF ed opzionale il person_id che però sarà utile per il futuro quando sarà deprecato il CF. Poi aggiorneremo tutti attraverso la documentazione e le linee guida su quali saranno le migliori pratiche da seguire per un cambio di paradigma.

Grazie

**Comment by denismarini** [comment]
Buongiorno @calogerocrapanzano,

Le comunico che su PDND c'è la possibilità di utilizzare il servizo C30 in modalità massiva  ElabMassivaAccertIdUnicoNazionale per ottenere gli IDANPR e aggiungerli in banca dati. 

Grazie

**Comment by calogerocrapanzano** [comment]
Buongiorno @denismarini 
ho avuto modo di interloquire direttamente con un referente Sogei, il quale mi ha indicato come servizio da utilizzare il **C015-servizioAccertamentoGeneralita**.

Questo servizio riceve in ingresso l'ID ANPR e restituisce le generalità, comprensive quindi di codice fiscale.

Grazie

**Comment by denismarini** [comment]
Ciao @calogerocrapanzano, molto bene e se vuoi sfruttare il massivo solo per IDANPR c'è quella che ti ho indicato,

Buono lavoro

**Comment by calogerocrapanzano** [comment]
Ciao @denismarini 

Si, in effetti potrebbe essere più comodo e performante salvare preventivamente una lista di IDANPR per tutte le anagrafiche studenti evitando di dover ripetere ogni volta la richiesta.

Grazie ancora!

**Comment by nicolabeghin** [comment]
Come comportarsi se alla richiesta di fruizione dell'e-service ANPR `C015-servizioAccertamentoGeneralita` nessuno risponde da un mese e/o se il servizio ANPR non é disponibile? É ok rispondere con 500 server error o é suggerito qualche altro codice specifico @denismarini ?

**Comment by denismarini** [comment]
Ciao @nicolabeghin,

Il C015 dovrebbe essere utile solo quando non si riceve il CF ma si riceve solo l'IDANPR, in tal caso può utilizzare il codice 503 Service Unavailable, ossia per indicare che il server non è in grado di gestire la richiesta temporaneamente, a causa del fatto che un servizio esterno non è disponibile. Questo codice suggerisce che il problema potrebbe essere risolto in un secondo momento.

Se per favore mi potrebbe indicare chi ha contattato per segnalare l'anomalia, di seguito i due casi:

- Se non vengono accettate le richieste di fruizione è una responsabilità del ministero dell'interno
- Se ci sono problemi tecnici (500/404 etc.) è responsabilità di Sogei

Ad ogni modo, consigliamo sempre di passare per i canali ufficiali, quindi tramite la mail di contatto presente in piattaforma, che nel caso del Mint è filippocarlo.viglianisi@interno.it

Ne approfitto per indicarla che esiste anche la possibilità di utilizzare il servizio C30 in modalità massiva ElabMassivaAccertIdUnicoNazionale per ottenere gli IDANPR e aggiungerli in banca dati in maniera asincrona.
