### ISSUE TITLE
IFS02.3 - Forse l'oggetto proof_education_course dovrebbe essere un array?

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#175]
Buonasera,
in merito alla response dell'API IFS02.3 https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/03_analysis/io_schema/IFS02.3-response.json , l'oggetto proof_education_course contenente (programme_type_code, programme_type_name, ecc. ed i relativi learnings) forse dovrebbe essere un array.

Ad es. uno studente che fosse iscritto/stato iscritto ad una laurea triennale e poi ad una laurea magistrale in teoria la response dovrebbe contenere un array proof_education_course con due oggetti:
- un primo oggetto per la laurea triennale (e relativi insegnamenti nell'array learnings)
- un secondo oggetto per la laurea magistrale (e relativi insegnamenti nell'array learnings)
cioè una risposta fatta tipo così (dati di esempio):

{
  "personal_data": {
    "tax_code": "RSSMRA80A01F205D",
    "person_id": "AB123456C"
  },
  "proof_education_course": [ {
    "programme_type_code": "MT",
    "programme_type_name": "Laurea Triennale (DM 270/04)",
    "degree_course_code": "1573961",
    "degree_course_name": "Ingegneria informatica",
    "degree_class_code": "MSLT32",
    "degree_class_name": "Ingegneria informatica",
"institute_code": "16",
    "institute_name": "Milano - Politecnico",
    "learnings": [
      {
        "attended_learning_name": "Esame 3",
        "start_date": "2020-10-13",
        "end_date": "2023-10-13",
        "grade_value": "30",
        "grading_scale_min": "18",
        "grading_scale_max": "30",
        "ects_credits_received": 6
      },
      {
        "attended_learning_name": "Esame 4",
        "start_date": "2020-10-13",
        "end_date": "2023-10-13",
        "grade_value": "30",
        "grading_scale_min": "18",
        "grading_scale_max": "30",
        "ects_credits_received": 6
      }
    ]
  },
   {
    "programme_type_code": "MS",
    "programme_type_name": "Laurea Magistrale (DM 270/04)",
    "degree_course_code": "1573960",
    "degree_course_name": "Ingegneria informatica",
    "degree_class_code": "MSLM32",
    "degree_class_name": "Ingegneria informatica",
"institute_code": "16",
    "institute_name": "Milano - Politecnico",
    "learnings": [
      {
        "attended_learning_name": "Esame 1",
        "start_date": "2020-10-13",
        "end_date": "2023-10-13",
        "grade_value": "30",
        "grading_scale_min": "18",
        "grading_scale_max": "30",
        "ects_credits_received": 6
      },
      {
        "attended_learning_name": "Esame 2",
        "start_date": "2020-10-13",
        "end_date": "2023-10-13",
        "grade_value": "30",
        "grading_scale_min": "18",
        "grading_scale_max": "30",
        "ects_credits_received": 6
      }
    ]
  }
 ]
}

Saluti.

Gualdani Alessandro

**Comment by denismarini** [comment]
Grazie mille @AlessandroGualdaniUniGe per l'indicazione, era un errore che abbiamo corretto!
