### ISSUE TITLE
dubbi su IFS03*

### ISSUE THREAD

**Issue by ebottacin** [italia/api-padigitale2026-misura1.3.1-uni-afam#176]
Buongiorno,

volevo segnalare una serie di dubbi sull'API IFS03

# FS03.3 - proof-tertiary-education-qualifications-level
`/proof-tertiary-education-qualifications-level`

* nella response sull'insieme `proof_qualification_relations`: è indicato il campo `has_parent_relations` cosa dovrebbe essere inserito in questo campo? nella descrizione viene riportata solo la traduzione del campo.

# IFS03.4 - proof-tertiary-education-qualifications-diploma-supplement
* nella response sull'insieme `attended_learning`: la documentazione dell'insieme indiica "Elenco corsi frequentati" ma nel dettaglio dello schema di attended learnings viene indicato "corsi frequentati" penso che sia un refuso e che si intendano solo i corsi superati.
* tra i dettagli di attend_learnings non vedo la data di superamento, c'è cfu, voto, voto_min, voto_max ma non la data. Sono presenti data di inizio (?) e data di fine corso. Va tracciato su data di fine corso la data di superamento ?

# Domande generali
* eql_level
* nqf_level
per i livelli europei e livelli nazionali esiste una enumeration sulla quale basare le descrizioni oppure possiamo inserire una descrizione del livello generica senza nessuna validazione della stringa?

**Comment by denismarini** [comment]
> Buongiorno,
> 
> volevo segnalare una serie di dubbi sull'API IFS03
> 
> # FS03.3 - proof-tertiary-education-qualifications-level
> `/proof-tertiary-education-qualifications-level`
> 
> * nella response sull'insieme `proof_qualification_relations`: è indicato il campo `has_parent_relations` cosa dovrebbe essere inserito in questo campo? nella descrizione viene riportata solo la traduzione del campo.
> 
La descrizione di questo campo è riportata in dettaglio nel readme.md
> # IFS03.4 - proof-tertiary-education-qualifications-diploma-supplement
> * nella response sull'insieme `attended_learning`: la documentazione dell'insieme indiica "Elenco corsi frequentati" ma nel dettaglio dello schema di attended learnings viene indicato "corsi frequentati" penso che sia un refuso e che si intendano solo i corsi superati.

Si, si intendono gli insegnamenti superati anche se non è richiesta la data di superamento

> * tra i dettagli di attend_learnings non vedo la data di superamento, c'è cfu, voto, voto_min, voto_max ma non la data. Sono presenti data di inizio (?) e data di fine corso. Va tracciato su data di fine corso la data di superamento ?
> 
> # Domande generali
> * eql_level
> * nqf_level
>   per i livelli europei e livelli nazionali esiste una enumeration sulla quale basare le descrizioni oppure possiamo inserire una descrizione del livello generica senza nessuna validazione della stringa?

Benissimo una descrizione del livello non esiste al momento una enumerazione,


@ebottacin mille grazie per il contributo
