### ISSUE TITLE
Suggerimento per esempio AFAM IFS01.1 

### ISSUE THREAD

**Issue by isidata23** [italia/api-padigitale2026-misura1.3.1-uni-afam#177]
Buongiorno,
Poichè sono stati forniti i dataset, relativamente all'esempio AFAM per IFS01.1, suggerisco che lo stesso può essere aggiornato come segue:

/*Esempio AFAM*/

{
    "degree_courses": [
        {
            "programme_type_code":"PL",  
            "programme_access":"Ammissione",
            "course_location":"058091,058039",
            "course_area":"DISCIPLINE INTERPRETATIVE",
            "degree_class_code":"L-3", 
            "degree_course_language":"IT",
            "degree_course_period_years":3,
            "degree_course_code":"100101", 
            "total_credits":180,
            "academic_year":"2023/2024"
        },
        {
            "programme_type_code":"SL", 
            "programme_access":"Ammissione",
            "course_location":"058091,058039",
            "course_area":"DISCIPLINE INTERPRETATIVE",
            "degree_class_code":"LM-45",  
            "degree_course_language":"IT,EN",
            "degree_course_period_years":2,
            "degree_course_code":"101056", 
            "total_credits":120,
            "academic_year":"2023/2024"
        },
        {
            "programme_type_code":"SL", 
            "programme_access":"Ammissione, Immatricolazione diretta",
            "course_location":"058091,058039",
            "course_area":"Discipline interpretative del jazz, delle musiche improvvisate e audiotattili",
            "degree_class_code":"LM-45",  
            "degree_course_language":"IT,EN",
            "degree_course_period_years":2,
            "degree_course_code":"101096",
            "total_credits":120,
            "academic_year":"2023/2024"
        }
    ]
    ,
    "meta":
    {
        "cursor":"" /*Non valorizzato o non presente nel caso in cui non siano presenti ulteriori paginazioni - Vedere esempi nello YAML*/
    }
}

**Comment by denismarini** [comment]
Ciao @isidata23,

Mille grazie per l'esempio utilissimo, però prima di utilizzarlo per aggiornare le specifiche riguardo agli esempi AFAM non capiamo perché l'oggetto programm_access non corrisponde all'enum {free, limited} si tratta di un refuso? 

cc @davidelongo-ey

Attendiamo vostro riscontro

**Comment by isidata23** [comment]
Scusate il ritardo, 
si era un refuso.
In realtà, se non ci sono dei regolamenti particolari interni, negli AFAM è sempre o Ammissione (Limited) o Immatricolazione diretta (Free) (dipende dal titolo di studio specialmente per le Accademie di BB.AA.); quindi va benissimo Free, Limited

**Comment by denismarini** [comment]
Mille grazie @isidata23
