### ISSUE TITLE
IFS03.3 - Forse l'oggetto proof_qualifications_level dovrebbe essere un array?

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#178]
Buongiorno,
in merito alla response dell'API IFS03.3 https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/03_analysis/io_schema/IFS03.3-response.json , l'oggetto proof_qualifications_level contenente (qualification_name, institute_code, ecc. ed i relativi ects_learnings) e l'esempio dello swagger forse dovrebbe essere un array.

Ad es. uno studente che fosse iscritto/stato iscritto ad una laurea triennale e poi ad una laurea magistrale in teoria la response dovrebbe contenere un array proof_qualifications_level con due oggetti:

un primo oggetto per la laurea triennale (e relativi insegnamenti nell'array ects_learnings)
un secondo oggetto per la laurea magistrale (e relativi insegnamenti nell'array ects_learnings)

cioè una risposta fatta tipo così (dati di esempio):
{
  "personal_data": {
    "tax_code": "RSSMRA80A01F205D",
    "person_id": "AB123456C"
  },
  "proof_qualifications_level": [ {
    "qualification_name": "Laurea in Scienze Aziendali",    
    "institute_code": "16",
    "institute_name": "Milano - Politecnico",
    "academic_qualification_date": "2022-07-01",
    "total_ects": 180,
    "eqf_level": "6° livello",
    "nqf_level": "I ciclo QF-EHEA",
    "has_parent_relation": null,
    "degree_course_duration_in_months": 36,
    "degree_course_duration_ects_credit": 180,
    "ects_learnings": [
      {
        "learning_name" : "Analisi matematica I e Geometria",
        "ects_credits": 10
      },
      {
        "learning_name" : "Fisica sperimentale",
        "ects_credits": 10
      },
      {
        "learning_name" : "Fisica tecnica",
        "ects_credits": 5
      }
    ]
  },
  {
    "qualification_name": "Laurea Magistrale in Scienze Aziendali",    
    "institute_code": "16",
    "institute_name": "Milano - Politecnico",
    "academic_qualification_date": "2024-03-01",
    "total_ects": 120,
    "eqf_level": "7° livello",
    "nqf_level": "II ciclo QF-EHEA",
    "has_parent_relation": null,
    "degree_course_duration_in_months": 24,
    "degree_course_duration_ects_credit": 120,
    "ects_learnings": [
      {
        "learning_name" : "Analisi matematica II e Geometria",
        "ects_credits": 10
      },
      {
        "learning_name" : "Fisica sperimentale II",
        "ects_credits": 10
      },
      {
        "learning_name" : "Fisica tecnica II",
        "ects_credits": 5
      }
    ]
  }
  ]
}

Saluti.

Gualdani Alessandro

**Comment by davidelongo-ey** [comment]
Grazie per la segnalazione, le modifiche proposte sono state riportate sul branch dev.

a presto
