### ISSUE TITLE
IFS03.4 - Discrepanza tra esempio e swagger

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#179]
Buongiorno,
in merito alla response dell'API IFS03.4 https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/03_analysis/io_schema/IFS03.4-response.json , l'oggetto proof_qualifications_diploma_supplement (contenente ects_credits_received, institute_name, ecc. ed i relativi attended_learnings) è un array mentre nello swagger è un oggetto.

Probabilmente dovrebbe essere un array: potete verificare ed allineare l'esempio e lo swagger?

Saluti.

Gualdani Alessandro

**Comment by davidelongo-ey** [comment]
Grazie per la segnalazione, abbiamo apportato la modifica suggerita nella issue

A presto
