### ISSUE TITLE
Nota su IFS02.3, IFS03.3, IFS03.4

### ISSUE THREAD

**Issue by ebottacin** [italia/api-padigitale2026-misura1.3.1-uni-afam#180]
Buongiorno,

volevo segnalare una puntualizzazione da inserire nella documentazione del readme (o meglio nello schema della response delle due api)

I seguenti elementi mappano le attività che lo studente ha sostenuto durante la carriera ritornata dall'api 
* IFS02.3  => learnings
* IFS03.3  => ects_learnings
* IFS03.4  => attendend_learnings

In IFS02.3 vengono indicate le caratteristiche previste dalle attività per poter essere esposte dall'api, immagino che la lista dovrebbe essere coerente tra le varie api, quindi inserirei in modo esplicito in tutte le API che l'insieme delle attività deve avere le seguenti caratteristiche

* attività superate o convalidate
* attività presenti a piano di studio approvato
* attività non sovrannumerarie

Enrico.

**Comment by davidelongo-ey** [comment]
Ciao Enrico,
grazie per i suggerimenti, le tue osservazioni sono state riportate come da tue indicazioni.
Il dettaglio delle modifiche puoi trovarle nel commit  #180 

A presto
