### ISSUE TITLE
IFS07.1 - Chiarimenti su filtri

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#181]
Buongiorno, 
abbiamo bisogno di un chiarimento nell’interpretazione della API IFS07.1, a seguito dell’introduzione dei parametri university_system_type e sync_mode.

Nella specifica OpenAPI è indicato che la chiave è l’hash del codice fiscale dello studente, quindi, per ogni codice fiscale (key hash), ci sarà un unico valore (value hash) relativo a tutti i titoli di studio dello studente.

Si consideri l’esempio di uno studente che ha conseguito una laurea vecchio ordinamento (pre-509) nel 2000 e poi una laurea magistrale (post-509) nel 2021: al codice fiscale dello studente (o meglio, al suo key hash) sarà associato un value hash, che ha valore H1 (calcolato sulla base dei valori di entrambe le lauree).

Ipotizziamo che alcuni giorni fa sia avvenuta una rettifica sulla laurea magistrale: viene quindi calcolato un nuovo value hash H2 (relativo a tutti i titoli di studio dello studente).

Si considerino le seguenti invocazioni dell’API IFS07.1:

university_system_type=old&sync_mode=full -> restituisce il nuovo hash H2 (dato che lo studente ha almeno una laurea pre-509)

university_system_type=new&sync_mode=full -> restituisce il nuovo hash H2 (dato che lo studente ha almeno una laurea post-509)

sync_mode=full -> restituisce il nuovo hash H2 (dal momento che bisogna restituire l'hash, a prescindere se la laurea è pre-509 o post-509)

university_system_type=old&sync_mode=incremental -> non restituisce il nuovo hash H2 (dal momento che, benché l’hash value sia cambiato da H1 ad H2, la variazione negli ultimi 2 anni è relativa ad una laurea post-509)

university_system_type=new&sync_mode=incremental -> restituisce il nuovo hash H2 (dal momento che la variazione negli ultimi 2 anni è relativa ad una laurea post-509)

sync_mode=incremental -> restituisce il nuovo hash H2 (dal momento che c'è stata almeno una variazione in una laurea negli ultimi 2 anni)

L’interpretazione sopra è giusta?

Ovvero, in pratica, per ogni codice fiscale (key hash) bisogna calcolare un unico value hash (relativo a tutti i titoli di studio dello studente), ma tenere traccia se viene calcolato per lauree pre-509, post-509 o entrambe e se sono occorse variazioni negli ultimi 2 anni su lauree pre-509, post-509 o entrambe: giusto?

Il dubbio origina, ad es., dal fatto che nella specifica OpenAPI https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS07-variazioni-titoli.yaml per il parametro university_system_type è indicato "Se questo parametro non è specificato, l'API restituisce i titoli accademici sia del vecchio che del nuovo ordinamento" come se ci fosse un value hash per ogni laurea ma, se il key hash è il codice fiscale, allora il value hash sarà necessariamente unico e calcolato sui valori di tutte le lauree dello studente (a meno di non mantenere hash diversi in base al pre/post 509, quindi hashtable diverse).

Saluti.

Gualdani Alessandro

**Comment by denismarini** [comment]
Buongiorno @AlessandroGualdaniUniGe,

Mille grazie per il suo utile contributo alla definizione delle specifiche delle API. 
Come da conversazione per le vie brevi abbiamo modificato la descrizione dei parametri d'ingresso del servizio IFS07.1. 
Inoltre per tutti i lettori metto in evidenza che la modalità incrementale della IFS07.1 restituisce tutti i **titoli conseguiti** (fa fede la data di conseguimento) e tutti quelli **rettificati** (fa fede la data di rettifica) negli ultimi 2 anni

Grazie!
