### ISSUE TITLE
IFS01 Offerta formativa: dubbio degree_course_cod

### ISSUE THREAD

**Issue by silviaavella** [italia/api-padigitale2026-misura1.3.1-uni-afam#183]
Buongiorno, 
relativamente all'API IFS01, troviamo due indicazioni diverse sulla valorizzazione del campo degree_course_cod.

Da questa pagina 
https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/tree/dev?tab=readme-ov-file#risorse-utili
si indicano gli open data come riferimento per estrarre i codici dei corsi

mentre da quest'altra pagina
https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/tree/dev?tab=readme-ov-file#ifs01-offerta-formativa

sembra si debba fare riferimento alle codifiche ANS fornite nel sito dell'osservatorio Cineca (https://osservatorio.mur.gov.it/)

Quale code deve essere indicato?
Vi ringrazio in anticipo,

**Comment by denismarini** [comment]
Buongiorno @silviaavella,

Ci scusi per il ritardo con il quale stiamo rispondendo, e la ringrazio per il suo prezioso contributo, provo a risponderle contestualmente di seguito

> Buongiorno, relativamente all'API IFS01, troviamo due indicazioni diverse sulla valorizzazione del campo degree_course_cod.
> 
> Da questa pagina https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/tree/dev?tab=readme-ov-file#risorse-utili si indicano gli open data come riferimento per estrarre i codici dei corsi

Era una indicazione solo a titolo di esempio quando ancora non erano pronti i dataset esposti dal MUR. Quindi, elimineremo questa parte sul readme.md per evitare di generare confusione. I dataset si trovano sul repository https://github.com/MIPA-CINECA/codifiche-mur
cc @davidelongo-ey 
> 
> mentre da quest'altra pagina https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/tree/dev?tab=readme-ov-file#ifs01-offerta-formativa
> 
> sembra si debba fare riferimento alle codifiche ANS fornite nel sito dell'osservatorio Cineca (https://osservatorio.mur.gov.it/)
Il repository corretto è a questo url https://github.com/MIPA-CINECA/codifiche-mur come correttamente indicato in questa sezione del readme.md
> 
> Quale code deve essere indicato? Vi ringrazio in anticipo,
Sempre sul repository https://github.com/MIPA-CINECA/codifiche-mur per le Università: Corsi.json oppure Corsi.csv

**Comment by davidelongo-ey** [comment]
riferimenti aggiornati inseriti nel Readme, vedere sezione "Risorse utili"

Saluti
