### ISSUE TITLE
degree_class_code in IFS01.1-response.json

### ISSUE THREAD

**Issue by isidata23** [italia/api-padigitale2026-misura1.3.1-uni-afam#184]
Buonasera
Nell'esempio del response per la IFS01.1 c'è il campo "degree_class_code"
https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/03_analysis/io_schema/IFS01.1-response.json

Mentre lo stesso non è presente nell'esempio response dello yaml
https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS01-offerta-formativa.yaml

Quale uso come riferimento per creare i response?

Grazie mille

Fabio Fonzo, ISIDATA

**Comment by denismarini** [comment]
Buongiorno @isidata23,

L'errore sta nel json, quindi la risposta della IFS01.1 non dovrebbe contenere il "degree_class_code". Procediamo a correggere la json.
cc @davidelongo-ey 

Fabio mille grazie per il tuo contributo
