### ISSUE TITLE
IFS01.2 - chiarimenti su transcodifiche per campo programme_access

### ISSUE THREAD

**Issue by lrollandi** [italia/api-padigitale2026-misura1.3.1-uni-afam#185]
Buongiorno,
nel nostro gestionale dell'offerta formativa, sono previsti i seguenti 4 valori per il campo in oggetto:

1- programmato
2- libero ---
3- libero --- con test di autovalutazione obbligatorio prima dell’immatricolazione
4- libero --- con valutazione dei requisiti di accesso

Per i primi due la mappatura per noi ovvia è rispettivamente sui seguenti 2 valori previsti dalla API:
1- Limited
2- Free

Vi chiediamo per contro se potete darci indicazione su come tradurre le altre due tipologie di accesso (3 e 4), rispetto ai valori previsti dalle specifiche dell' API IFS01.2.

Grazie mille in anticipo
Buona giornata
Loredana Rollandi

**Comment by denismarini** [comment]
Le tipologie di accesso (3,4) possono essere considerate come modalità "Free", poiché rappresentano informazioni utilizzate da Universitaly per fornire un orientamento agli studenti nella scelta del percorso formativo. Ulteriori dettagli saranno disponibili all'interno del portale dell'istituto di interesse.

Spero di aver chiarito il suo dubbio. Per ulteriori informazioni, non esiti a scrivere qui o a creare una nuova discussione.

Grazie per la collaborazione e le auguro una buona giornata
Denis Marini

**Comment by lrollandi** [comment]
Buon pomeriggio Denis,
grazie per il chiarimento.
Chiudo la issue.
Buona serata
Loredana
