### ISSUE TITLE
Dubbio formato request IFS02.1

### ISSUE THREAD

**Issue by s-cenni** [italia/api-padigitale2026-misura1.3.1-uni-afam#186]
Buongiorno,
ho un dubbio relativo a questa request: https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/03_analysis/io_schema/IFS02.1-request.json
Sia nell'esempio sia nella documentazione https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam?tab=readme-ov-file#ifs02-iscrizioni non viene citato il campo institute_code presente però nel file YAML:
https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS02-iscrizioni.yaml#L1016

è un campo da gestire oppure è nello yaml per un refuso? 
Grazie mille

**Comment by denismarini** [comment]
Ciao @s-cenni,
È stato aggiunto l'attributo institute_code nella richiesta per abilitare l'interazione ANIS - ANS, utilizzando le medesime specifiche. Questo è necessario poiché ANS è multi-istituto e quindi ANIS deve specificare ad ANS per quale istituto sta richiedendo i dati. Nel caso dell'implementazione delle API per il singolo istituto, come nel vostro caso, potete ignorare la gestione del codice istituto nella richiesta poiché è implicito e non vi sarà inviato essendo opzionale.

Spero di averti risposto ed etichetto come FAQ  questa domanda che sarà sicuramente utile anche ai colleghi,

Ti ringrazio molto per la collaborazione,

Denis

**Comment by s-cenni** [comment]
Grazie mille!
