### ISSUE TITLE
Valorizzazione campi opzionali

### ISSUE THREAD

**Issue by silviaavella** [italia/api-padigitale2026-misura1.3.1-uni-afam#187]
Buonasera,
non c'è chiaro se nel caso di campi NON obbligatori, possiamo restituire il valore NULL anche se non è specificato oppure non deve essere proprio restituita la properties.

Ad esempio, per l'IFS01 le properties sembrano essere tutte opzionali.

Vi ringrazio in anticipo

**Comment by denismarini** [comment]
Buonasera @silviaavella,

Per non vincolare eccessivamente la realizzazione delle API, abbiamo reso opzionali molti attributi, soprattutto in questa fase iniziale di ingresso alla PDND. Tuttavia, è consigliabile fornire la maggior parte delle informazioni richieste, qualora siano disponibili. Per quanto riguarda gli attributi opzionali, potete scegliere di restituire un valore nullo oppure di ometterli completamente.

Spero di essere stato chiaro e rimango a disposizione per ulteriori richieste

Mille grazie

**Comment by NETTunoPA** [comment]
Buongiorno, 
quindi al momento gli unici campi obbligatori, cioè senza i quali non va restituito l'oggetto stesso, sono quelli specificati nel required nell'Openapi? 

Per esempio IFS02, oggetto proof_enrollment:
required:
        - enrollment_date
        - expected_graduation_date
        - country_of_academic_institution
        - institute_name
        - institute_code
        - degree_class_code
        - degree_course_name
        - degree_course_code
        - programme_type_name
        - programme_type_code

**Comment by denismarini** [comment]
Buongiorno @NETTunoPA ,

Confermo che sono quelli specificati nel required gli obbligatori e come ho indicato alla collega è comunque consigliato fornire la maggior parte delle informazioni richieste, qualora siano disponibili. 

Nel caso da voi riportato anche il degree_class_code non è obbligatorio quando non esiste (per esempio per i master universitari) quindi correggeremo il refuso.

Rimango a disposizione per ulteriori richieste

Mille grazie
