### ISSUE TITLE
IFS04.4 - Chiarimento su obbligatorietà attribute_name di una issue

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#188]
Buongiorno,
in merito all'API IFS04.4, l'attributo attribute_name di una issue (nell'ambito degli oggetti personal_data -> issues e enrollment -> issues), nello schema OpenAPI https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS04-rettifica-iscrizioni.yaml l'attribute_name risulta required ma nullable nello schema.
Invece, nell'API IFS05.4, l'attribute_name di una issue (nell'ambito degli oggetti personal_data -> issues e qualifications -> issues) risulta non required ma nullable.

Come va interpretata la differenza tra le due API di cui sopra nell'obbligatorietà o meno dell'attribute_name?
E come andrebbe interpretata una richiesta con una issue senza un attribute_name o con un attribute_name null?

Saluti.

Gualdani Alessandro

**Comment by denismarini** [comment]
Ciao @AlessandroGualdaniUniGe,

Grazie mille per i feedback che ci fornisci. In risposta al tuo messaggio, abbiamo rimosso l'obbligatorietà di attribute_name e lasciato il campo nullable. In questo modo, è possibile decidere se omettere il campo oppure riportare null nel caso si desideri segnalare una issue generica, non specifica per un attributo. Questo intervento è stato implementato sia per IFS04.4 che per IFS05.4.

A presto,

Denis
