### ISSUE TITLE
IFS02, IFS03 semantic error

### ISSUE THREAD

**Issue by francescosangiovanni** [italia/api-padigitale2026-misura1.3.1-uni-afam#189]
Buongiorno,
sviluppando le api delle IFS02 e IFS03 abbiamo notato che alcune response non sono conformi agli esempi forniti.
Infatti, alcuni oggetti che dagli esempi possono essere degli array, sono definiti come oggetti sui rispettivi YAML. 
Anche se i file YAML hanno priorità rispetto agli esempi, pensiamo che ci siano degli errori da correggere come confermato anche dalla validazione effettuata tramite l'editor online di swagger:

IFS02: 
Semantic error at components.schemas.proof_education_course
Schemas with 'type: array', require a sibling 'items: ' field
Jump to line 600

IFS03:
Semantic error at components.schemas.proof_qualifications_diploma_supplement
Schemas with 'type: array', require a sibling 'items: ' field
Jump to line 650
Semantic error at components.schemas.proof_qualifications_level
Schemas with 'type: array', require a sibling 'items: ' field
Jump to line 803

Tali file vengono usati anche per generare, con un apposito plugin, le classi java usate per implementare le API.
Al momento abbiamo modificato all'interno del nostro progetto i file yaml in modo da generare correttamente le classi, ma ogni modifica fatta su questi yaml sul repository ufficiale, richiede poi l'intervento manuale prima della nuova generazione.

E' possibile correggere questi errori semantici?

Grazie

Francesco Sangiovanni

**Comment by denismarini** [comment]
Buonasera @francescosangiovanni,

Vi ringraziamo molto per averci segnalato questi errori. Provvederemo a correggerli entro questa settimana e vi informeremo non appena saranno risolti.

Nel frattempo, se doveste riscontrare ulteriori problemi durante l'implementazione, non esitate a farcelo sapere.

Buon lavoro!

--> @davidelongo-ey

**Comment by denismarini** [comment]
Buonasera @francescosangiovanni ,

La issue è stata risolta,

Mille grazie
