### ISSUE TITLE
IFS04.2, IFS04.3, IFS05.2, IFS05.3 - Response in caso di file_code inesistente

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#192]
Buonasera,
in merito alle API IFS04.2, IFS04.3, IFS05.2, IFS05.3, nel caso in cui nella request venisse passato un file_code inesistente, quale deve essere la risposta ovvero cosa deve essere restituito come response?
Un JSON vuoto?

Saluti.

Gualdani Alessandro

**Comment by denismarini** [comment]
Ciao @AlessandroGualdaniUniGe,

**Nel caso della 4.3 e 5.3** se il file_code non esiste, è restituito una risposta con response_code "rejected". Vedere anche la issue #191.
**Nel caso della 4.2 e 5.2** si può rispondere con 400 Bad request oppure 200 con null

Grazie
