### ISSUE TITLE
IFS09.1 - Dubbio su vincoli attributi della response

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#193]
Buongiorno,
in merito alla specifica OpenAPI della IFS09.1 https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS09-iscrizioni-per-corso.yaml gli attributi della response:

male_enrollment_count
female_enrollment_count

sono obbligatori, nullable e con un range di valori da 1 a 9999999.

Sulla base dei vincoli di cui sopra, se per qualche corso di studio non ci fossero studenti di sesso maschile o femminile, non possiamo quindi indicare: male_enrollment_count: 0 oppure female_enrollment_count: 0 ma dobbiamo necessariamente indicare: male_enrollment_count: null oppure female_enrollment_count: null?

Saluti.

Gualdani Alessandro

**Comment by davidelongo-ey** [comment]
grazie per la segnalazione, abbiamo provveduto a imputare il valore minimo consentito per i campi 
- female_enrollment_count
- male_enrollment_count

Al valore 0 come suggerito

Saluti
