### ISSUE TITLE
IFS09.1 - Dubbi su iscritti a lauree del vecchio ordinamento

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#195]
Buongiorno,
in merito all'API IFS09.1 nella specifica OpenAPI https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS09-iscrizioni-per-corso.yaml la response prevede l'attributo degree_course_code obbligatorio.

Noi abbiamo ancora degli iscritti a corsi di laurea vecchio ordinamento (per cui non era previsto il DEGREE_COURSE_CODE inteso come chiave anagrafe bensì il codice USTAT utilizzato dall'Ufficio di Statistica), quindi per tali iscritti il DEGREE_COURSE_CODE non ci sarebbe: dobbiamo escludere dai conteggi gli iscritti ai corsi di laurea del vecchio ordinamento?

Saluti.

Gualdani Alessandro

**Comment by denismarini** [comment]
Buongiorno @AlessandroGualdaniUniGe,

Stiamo procedendo ad eliminare l'obbligatorietà del degree_class_code (refuso) e stiamo rendendo nullable il degree_course_code in questo modo puoi collassare tutti i conteggi su un item privo di degree_course_code(quello indicato dal MUR nel repository del CINECA) con il valore null

Grazie
