### ISSUE TITLE
IFS03 - Dubbio interazione con IFS07

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#196]
Buongiorno,
ho un dubbio su scenari tipo il seguente:

1. lo studente X ha una variazione su una laurea del vecchio ordinamento
2. viene invocata la IFS07.1 con academic_system=old e e sync_mode=full, quindi viene restituito (assieme a quello di altri studenti) l'hash dello studente X
3. ANIS invoca la IFS03.1 con il codice fiscale (tax_code) dello studente X; tuttavia, la specifica OpenAPI https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS03-titoli.yaml prevede che nella response l'attributo degree_course_code sia obbligatorio, quindi come facciamo a restituire il dettaglio di un titolo di studio del vecchio ordinamento dal momento che i corsi di laurea del vecchio ordinamento non hanno degree_course_code?

Il dubbio può essere generalizzato ovvero come dobbiamo trattare i corsi di laurea/titoli (sia IFS02 che IFS03) nel caso del vecchio ordinamento, che non prevedono un degree_course_code, in base al repository del MUR https://github.com/MIPA-CINECA/codifiche-mur/tree/main ?
Non dobbiamo selezionare iscrizioni/titoli del vecchio ordinamento in nessuna estrazione? Però in tal caso verrebbe un po' meno l'utilità del filtro academic_system=old della IFS07.1.

Teoricamente, per il vecchio ordinamento, si potrebbe valorizzare il campo degree_course_code con il codice univoco USTAT utilizzato dall'Ufficio di Statistica (similmente a come viene fatto per l'invio dei dati all'Anagrafe Nazionale Studenti ANS) anche se il significato non è proprio lo stesso dal momento che il codice univoco USTAT non è storicizzato per coorte mentre la chiave anagrafe dei corsi di studio D.M. 509 e D.M. 270/2004 è storicizzata per coorte (oltre ad essere più "dettagliata", riferendosi ad una specifica sede, curriculum, classe di laurea).

Saluti.

Gualdani Alessandro

**Comment by AlessandroGualdaniUniGe** [comment]
Buonasera @denismarini ,
ho aperto la issue: https://github.com/MIPA-CINECA/codifiche-mur/issues/5

Saluti.

Gualdani Alessandro

**Comment by denismarini** [comment]
Buongiorno @AlessandroGualdaniUniGe,

Mille grazie!

**Comment by AlessandroGualdaniUniGe** [comment]
Buongiorno,
aggiungo un'ulteriore considerazione a quanto sopra: nel caso in cui si prevedesse di restituire anche i titoli di studio del vecchio ordinamento, verosimilmente andrebbero adeguati alcuni campi della response, ad es. nella IFS03.3:

degree_course_duration_ects_credit
total_ects

andrebbero resi nullable perché, per i corsi di laurea del vecchio ordinamento, non erano previsti crediti.

Saluti.

Gualdani Alessandro

**Comment by denismarini** [comment]
Ciao @AlessandroGualdaniUniGe,

Ti ringrazio per la segnalazione, stiamo raffinando le obbligatorietà e i nullable per i servizi SDG. Comunque nel caso l'attributo non è obbligatorio puoi anche non restituirlo e di fatto è come restituire null, comunque aggiungeremo anche il nullable.

cc @davidelongo-ey
