### ISSUE TITLE
IFS03.3 - Obbligatorietà dell'array proof_qualifications_level

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#197]
Buongiorno,
in merito all'API IFS03.3 nella specifica OpenAPI https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS03-titoli.yaml risulta indicato:

required:
        - personal_data
        - proof_qualification_level

ma il nome dell'array si chiama: proof_qualification**s**_level (ovvero al plurale).

Saluti.

Gualdani Alessandro

**Comment by davidelongo-ey** [comment]
modificata obbligatorietà per proof_qualifications_level (ovvero al plurale).

**Comment by denismarini** [comment]
@AlessandroGualdaniUniGe procediamo a chiudere la issue con la correzione apportata grazie alle tue indicazioni,

Mille grazie
