### ISSUE TITLE
IFS03.4 - Obbligatorietà dell'array proof_qualifications_diploma_supplement

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#198]
Buongiorno,
in merito all'API IFS03.4 nella specifica OpenAPI https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS03-titoli.yaml risulta indicato:

required:
        - personal_data
        - proof_qualification_diploma_supplement

ma il nome dell'array si chiama: proof_qualification**s**_diploma_supplement (ovvero al plurale).

Saluti.

Gualdani Alessandro

**Comment by davidelongo-ey** [comment]
modificata obbligatorietà per proof_qualifications_diploma_supplement (ovvero al plurale).
