### ISSUE TITLE
stato-rettifiche-studente.yaml and ref not found

### ISSUE THREAD

**Issue by rockmesh** [italia/api-padigitale2026-misura1.3.1-uni-afam#2]
in [stato-rettifiche-studente.yaml](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/next/stato-rettifiche-studente.yaml)

gli endpoint `'/rettifiche-anagrafica/{taxCode}'` e `'/rettifica-anagrafica/{rectificationId}'` dovrebbero anche restituire `404 Student/ID not found`

**Comment by AulicinoDiego** [comment]
aggiunte le response 404 dove mancavano
