### ISSUE TITLE
Correggere il pattern regex di Name e Family name

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#200]
La regex attuale ^[p{L}} ,.'-\s''-Ӑ]+$   non è validata correttamente, da correggere
@davidelongo-ey @asm75

**Comment by davidelongo-ey** [comment]
pattern modificato in ^[p{L}} ,.'\s''-Ӑ]+$

**Comment by davidelongo-ey** [comment]
^[\p{L}\p{M}'’\- ]+$

**Comment by denismarini** [comment]
Pattern modificato con ^[\p{L}\p{M}'’\- ]+$
@asm75 attendiamo tuo riscontro e mille grazie per l'indicazione
