### ISSUE TITLE
Dubbi contenuto IFS02.1 e IFS02.2

### ISSUE THREAD

**Issue by silviaavella** [italia/api-padigitale2026-misura1.3.1-uni-afam#201]
Buongiorno, abbiamo dei dubbi sui due endpoint in oggetto.

IFS02.1
Acquisizione del dettaglio delle ultime iscrizioni per corso di studi negli ultimi tre anni accademici di una studentessa o di uno studente

IFS02.2
Acquisizione delle prove riguardanti l'ultima iscrizione a ogni corso di studi di istruzione terziaria di una studentessa/studente negli ultimi 3 anni accademici

In entrambi i casi si parla di iscrizioni ma dalla response sembrebbe invece si debbano inviare i dati della carriera.
Per uno studente con le seguenti iscrizioni.
2021/2022 iscrizione al terzo anno triennale corso A
2022/2023 iscrizione al primo anno magistrale corso B
2023/2024 iscrizione al secondo anno magistrale Corso B

cosa dovremmo inviare?In particolare, cosa si intende per prove?
L'esempio purtroppo non è molto esplicativo.

Vi ringrazio in anticipo, saluti
Silvia

**Comment by denismarini** [comment]
Buongiorno Silvia,

Partendo dal suo esempio dovreste restituire i seguenti item, ossia le ultime iscrizioni per corso e non la cariera per IFS02.1 e IFS02.2:
2021/2022 iscrizione al terzo anno triennale corso A
2023/2024 iscrizione al secondo anno magistrale Corso B

Il termine "prova" è una terminologia derivata dalle specifiche SDG europee e in questo caso si intende "la prova che uno studente sia iscritto o sia stato iscritto" ed è sufficente l'utima iscrizione per ogni corso negli ultimi 3 anni accademici, quindi se l'invocazione dell'API fosse oggi gli anni accademici utili sono 2023/2024 2022/2023 2021/2022

Mille grazie

**Comment by silviaavella** [comment]
Grazie mille,  quindi concettualmente i due endpoint devono restituire le stesse iscrizioni, gli stessi record.

Grazie in anticipo

**Comment by denismarini** [comment]
Esatto concettualmente restituiscono le stesse informazioni ma sono dedicati al momento a fruitori diversi, la 2.1 ad ANIS la 2.2 a SDG e la 2.1 **non** ha la data di iscrizione come da decreto ANIS

**Comment by denismarini** [comment]
Buon pomeriggio @silviaavella,

Questo stato è utilizzato dall'utente per compiere azioni sul proprio sistema. L'API IFS02.1 è stata concepita principalmente per alimentare ANIS ma può essere utilizzata anche da altri enti della Pubblica Amministrazione (PA). Considerato che attraverso ANIS, lo studente può visualizzare e generare le attestazioni delle sue iscrizioni.

ANIS utilizza questo stato per:

abilitare la visualizzazione delle iscrizioni e la generazione delle attestazioni con stato "active",
consentire la sola visualizzazione delle attestazioni con stato "wait",
impedire la visualizzazione delle attestazioni con stato "inactive".
Pertanto, l'istituto definisce lo stato di un'iscrizione in base a questi criteri. Ad esempio, alcuni istituti potrebbero considerare attive le iscrizioni per le quali è già stato effettuato il pagamento della retta, mentre altri no.

È importante notare che le iscrizioni attive sono "le ultime per ogni corso negli ultimi 3 anni accademici". Di conseguenza, se uno studente non si iscrive dopo 3 anni, le sue iscrizioni non devono essere inviate ad ANIS, oppure devono essere inviate come inattive.

Per esempio, uno studente che si è laureato nel 2021/2022 ha un'iscrizione "inactive" e il relativo titolo di laurea.

Spero di averla aiutata e buon lavoro,
