### ISSUE TITLE
Govway API gateway for PDND

### ISSUE THREAD

**Issue by nicolabeghin** [italia/api-padigitale2026-misura1.3.1-uni-afam#202]
Given https://govway.org is the [suggested](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/issues/157) Open Source API Gateway that implements the authentication protocol for PDND https://developers.italia.it/it/software/link-it-govway-7218c1.html

would it be possible to documentation on how it should be configured for PDND purposes?

thanks a lot
nicola

**Comment by denismarini** [comment]
Hi @nicolabeghin,

We don't have a specific example to provide you for integrating the Govway API Gateway with the PDND. However, the documentation for this framework includes information regarding that. 

The choice of API Gateway depends on your software architecture, and there are many other API Gateway solutions you can use. My recommendation is to refer to the PDND documentation to select the API Gateway that best fits your architecture for integrating with the PDND. 

Finally, please note that integration with the PDND does not necessarily require the use of an API Gateway for service delivery.

Thanks

**Comment by nicolabeghin** [comment]
I finally got to have a working govway instance both for UAT and PROD PDND - for anyone interested, feel free to contact me privately, the configuration is pretty complex and convoluted
