### ISSUE TITLE
[IFSX] Voto espresso in virgola mobile 

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#203]
Cambiare il pattern del voto da poter esprimere anche in virgola mobile con 4 cifre numeriche.

cc @davidelongo-ey @isidata23

**Comment by davidelongo-ey** [comment]
modificato pattern regex in ^(\d+(.\d{1,2})?|\d+L|QUALIFIED)$
