### ISSUE TITLE
IFS01.2 : chiarimenti su learning_code e dettaglio insegnamenti con più edizioni

### ISSUE THREAD

**Issue by lrollandi** [italia/api-padigitale2026-misura1.3.1-uni-afam#204]
Gentilissimi,
abbiamo questi due dubbi:
- in merito al learning_code è richiesto l'utilizzo di una codifica specifica? 
- per quanto riguarda gli insegnamenti erogati su più edizioni, nel dettaglio dell'offerta è necessario ripetere il record insegnamento n volte quante sono le edizioni?

Grazie in anticipo
Buona serata
Loredana Rollandi

**Comment by denismarini** [comment]
Buongiorno @lrollandi,

L'API IFS01 è progettata per alimentare il portale Universitaly con informazioni orientative destinate agli studenti, piuttosto che con dettagli specifici sulla programmazione accademica. Gli studenti potranno trovare le informazioni dettagliate e la programmazione precisa direttamente sul portale dell'istituto. Pertanto, è possibile ripetere il medesimo codice o aggiornare l'edizione in base all'importanza e alla rilevanza per l'orientamento degli studenti, soprattutto quelli stranieri, che troveranno poi i dettagli necessari sul sito dell'istituto.

Spero di aver capito correttamente la domanda e di aver risposto ai suoi dubbi.

Mille grazie
