### ISSUE TITLE
Problema espressione regolare tax_code

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#206]
Buonasera,
in merito all'espressione regolare del tax_code riportata nello swagger, ad es., IFS02 https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS02-iscrizioni.yaml abbiamo notato che non valida determinati codici fiscali, compreso quello di esempio.

Cioè il codice fiscale di esempio:

RSSMRA80A01F205D

non passa l'espressione regolare:

^(?:[A-Z][AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}(?:[\dLMNP-V]{2}(?:A-EHLMPR-T|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM]|[AC-EHLMPR-T][26NS][9V])|(?:[02468LNQSU][048LQU]|[13579MPRTV][26NS])B[26NS][9V])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M]0L)[A-Z]$

così come altri codici fiscali validi per l'Agenzia delle Entrate.

Saluti.

Gualdani Alessandro

**Comment by denismarini** [comment]
Ciao @AlessandroGualdaniUniGe,

Ora dovrebbe esserci il pattern corretto, ossia il seguente:

`^(?:^(?:[A-Z][AEIOU][AEIOUX]|[B-DF-HJ-NP-TV-Z]{2}[A-Z]){2}(?:[\dLMNP-V]{2}(?:[A-EHLMPR-T](?:[04LQ][1-9MNP-V]|[15MR][\dLMNP-V]|[26NS][0-8LMNP-U])|[DHPS][37PT][0L]|[ACELMRT][37PT][01LM]|[AC-EHLMPR-T][26NS][9V])|(?:[02468LNQSU][048LQU]|[13579MPRTV][26NS])B[26NS][9V])(?:[A-MZ][1-9MNP-V][\dLMNP-V]{2}|[A-M][0L](?:[1-9MNP-V][\dLMNP-V]|[0L][1-9MNP-V]))[A-Z]$)`

Grazie
