### ISSUE TITLE
IFS03 + IFS05 + IFS08 - Format 'Int32' is incompatible with schema type 'string' and 'integer'

### ISSUE THREAD

**Issue by nicolabeghin** [italia/api-padigitale2026-misura1.3.1-uni-afam#207]
Some validation errors from given YAMLs for IFS03 + IFS05 + IFS08:

`qualification_grading_scale_minimum_grade`
> Format 'Int32' is incompatible with schema type 'string' (code: 137)

    qualification_grading_scale_minimum_grade:
      type: string
      format: int32

`isee_min_value` and `isee_max_value`
> Format 'Int32' is incompatible with schema type 'integer' (code: 137)

Workarond: remove the `"format": "int32"`

**Comment by denismarini** [comment]
Thanks @nicolabeghin,

We will address the issue you reported as soon as possible.
cc @davidelongo-ey

**Comment by denismarini** [comment]
@davidelongo-ey the minimum and maximum should be float and not a string
