### ISSUE TITLE
degree_course_code not available for each academic year for AFAM

### ISSUE THREAD

**Issue by nicolabeghin** [italia/api-padigitale2026-misura1.3.1-uni-afam#208]
AFAM codes for `degree_course_code` are not available for each academic year in https://github.com/MIPA-CINECA/codifiche-mur/tree/main/AFAM
<img width="740" alt="image" src="https://github.com/user-attachments/assets/0b8baf77-c1c4-44b1-a0de-690aede67394">

while they are available for UNIVERSITA https://github.com/MIPA-CINECA/codifiche-mur/tree/main/Universita
<img width="1067" alt="image" src="https://github.com/user-attachments/assets/7b8516b9-873f-4b73-b463-ab8650447842">

How is this expected to be handled given `degree_course_code` is a key for a lot of `IFS*` apis? It's particularly important for `IFS01.02` where the `degree_course_code` is used as a primary key to retrieve the details of a given course.

thanks

**Comment by denismarini** [comment]
Hi @nicolabeghin,

You can find information at this [link](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam?tab=readme-ov-file#globe_with_meridians-ifs012---educational-offering-detail). If this information is not sufficient, please open an issue on the repository managed by CINECA [MIPA-CINECA](https://github.com/MIPA-CINECA/codifiche-mur/issues)

I hope this helps!

**Comment by nicolabeghin** [comment]
Created new MIPA-CINECA issue as suggested https://github.com/MIPA-CINECA/codifiche-mur/issues/6 since this is not enough
> Nelle AFAM il degree_course_code è lo stesso per tutti gli anni accademici della coorte

It's clearly wrong if no academic year code is provided
> Nella richiesta l'attributo degree_course_code è obbligatorio ed individua in modo univoco la combinazione: Corso, Classe, anno accademico della coorte, sede

In this way it goes against the logic of the services since it's not possible to use `degree_course_code` for IFS01.02 if there's no indication on what academic year has to be referenced

**Comment by denismarini** [comment]
Hi @nicolabeghin , we wait for an answer by CINECA and MUR in the other repository

> In this way it goes against the logic of the services since it's not possible to use `degree_course_code` for IFS01.02 if there's no indication on what academic year has to be referenced

> Nella risposta è sufficente includere il solo primo anno di corso dell’offerta formativa disponibile per la coorte identificata dal codice corso inviato come parametro di ingresso nella richiesta

If can help try to read even the answer to this issue https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/issues/204#issuecomment-2252519547
