### ISSUE TITLE
Grade "Lode e menzione"

### ISSUE THREAD

**Issue by nicolabeghin** [italia/api-padigitale2026-misura1.3.1-uni-afam#209]
How to express a grade like "30 e lode con menzione"?
The regexp does not accept `30LM` only `30L`

thanks

**Comment by denismarini** [comment]
Hi @nicolabeghin,

The grade value you mentioned, "30 e lode con menzione," is represented as "30L"

Thank you for your report!

**Comment by nicolabeghin** [comment]
Thanks, closing
