### ISSUE TITLE
How to validate e-services published in UAT (Collaudo)

### ISSUE THREAD

**Issue by nicolabeghin** [italia/api-padigitale2026-misura1.3.1-uni-afam#210]
Hi would it be possible to document how to validate/test e-services published in UAT (Collaudo) environment as per https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/06_deployment/Guida_erogazione_e-service_Universit%C3%A0_e_AFAM.pdf ? 

On a high level as far as I understand
1. [create keypair](https://docs.pagopa.it/interoperabilita-1/manuale-operativo/generare-e-caricare-chiavi-di-sicurezza#come-generare-le-chiavi) and load public key in PDND webui
2. create assertion with https://selfcare.uat.interop.pagopa.it/ui/data/it/create_client_assertion.py
3. create voucher with POST to https://auth.uat.interop.pagopa.it/token.oauth2
4. invoke e-service with header `Authentication: Bearer XXX` where `XXX` is voucher from previous step

**Comment by denismarini** [comment]
Hi @nicolabeghin,

What you have proposed is fine, following the PDND manuals. If it can be useful, you can use this gateway for the integration of the service provider with PDND: [Govway](https://govway.org/). You can write the test client using Postman.

We are still defining the technical process for the "Asserverazione." I recommend you publish on PDND exactly the same OpenAPI from this repository, changing only the info section. Run the tests as I recommended before, using Postman or other clients to test the API.

Thanks
