### ISSUE TITLE
[IFS01.2] Dataset AFAM per discipline

### ISSUE THREAD

**Issue by NETTunoPA** [italia/api-padigitale2026-misura1.3.1-uni-afam#213]
Buongiorno, 
nell' esempio di response viene ancora riportato /*in attesa di dataset*/ in corrispondenza di alcuni campi. 
Dove possiamo reperire l'elenco delle discipline con relativi codici?

Grazie per la collaborazione

**Comment by denismarini** [comment]
Buongiorno,

Ho corretto il refuso da Lei indicato. I dataset pubblici esposti dal MUR per la corretta implementazione delle API li trova su questo repository https://github.com/MIPA-CINECA/codifiche-mur gestito dal CINECA. Per qualsiasi richiesta di dettaglio e segnalazione può aprire una issue in questo repository.

Mille grazie!
