### ISSUE TITLE
IFS07 definizione dei tipi enumerativi academic_system e sync_mode

### ISSUE THREAD

**Issue by francescosangiovanni** [italia/api-padigitale2026-misura1.3.1-uni-afam#215]
Buongiorno,
utilizzando il plugin openapi per generare le classi java a partire dallo YAML, abbiamo degli errori in fase di chiamata alla API della IFS07 in quanto non vengono validati correttamente i campi academic_system e sync_mode.
Questo perché i due campi vengono annotati nel seguente modo:
  @Size(min = 1, max = 256) 
derivanti dalle proprietà dello YAML:         
          minLength: 1
          maxLength: 256

Essendo tali paramentri dei tipi enum, è possibile rimuovere queste proprietà dalla loro definizione?
Inoltre nella descrizione dell'academic_system c'è scritto  _"3. Se questo parametro non è specificato, l'API si riferisce ai i titoli accademici sia del vecchio che del nuovo ordinamento."_, però poi è definito come "nullable: false", è da correggere anche questo valore?

Grazie

**Comment by denismarini** [comment]
Buongiorno @francescosangiovanni,

Abbiamo corretto tutte le segnalazioni che ci ha comunicato in questa issue, https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/commit/53e0e4c3b8a6c8ac072f28af26cde9440fa02428

Mille grazie per la collaborazione
