### ISSUE TITLE
Differenze tra response IFS04.2 e IFS05.2 e tra esempi

### ISSUE THREAD

**Issue by AlessandroGualdaniUniGe** [italia/api-padigitale2026-misura1.3.1-uni-afam#216]
Buonasera,
le specifiche OpenAPI della response IFS04.2 https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS04-rettifica-iscrizioni.yaml e della response IFS05.2 https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS05-rettifica-titoli.yaml che, un tempo, avevano lo stesso formato (direi fino al commit https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/commit/d4a74596d21867abe73728db53c14fe5b43458bd escluso) , ora differiscono ovvero:

La response della IFS04.2 restituisce un oggetto fatto, ad es., come segue:

{
  "enrollment_change_request": [
    {
      "file_status": "approved",
      "file_code": "6d183bc572f6b200015a4167",
      "message": "testo messaggio"
    },
    {
      "file_status": "rejected",
      "file_code": "6d183b54654127dfhh15a4167",
      "message": "testo messaggio"
    }
  ]
}

Invece la response della IFS05.2 restituisce un array fatto, ad es., come segue:

[
  {
    "file_status": "approved",
    "file_code": "6d183bc572f6b200015a4167",
    "message": "testo messaggio"
  },
  {
    "file_status": "rejected",
    "file_code": "6d183b54654127dfhh15a4167",
    "message": "testo messaggio"
  }
]

Inoltre, l'esempio https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/03_analysis/io_schema/IFS05.2-response.json della response IFS05.2 è diverso (ovvero restituisce un oggetto) rispetto all'esempio presente nella specifica OpenAPI https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS05-rettifica-titoli.yaml (riportato sopra, che restituisce un array).

Sarebbe preferibile allineare gli schemi/esempi delle IFS04.2 e IFS05.2 in modo da far combaciare il formato delle response (ovvero in modo che restituiscano entrambe un oggetto oppure entrambe un array), dato che si tratta di API simili (IFS04.2 per le iscrizioni e IFS05.2 per i titoli di studio).

Saluti.

Gualdani Alessandro

**Comment by denismarini** [comment]
Ciao @AlessandroGualdaniUniGe,

Grazie della segnalazione, ci lavoriamo!

**Comment by denismarini** [comment]
Ciao @AlessandroGualdaniUniGe,

Abbiamo corretto ed allineato alla IFS04.2,

Grazie
