### ISSUE TITLE
IFS02.3 - problema generazione lista Java da file yaml

### ISSUE THREAD

**Issue by s-cenni** [italia/api-padigitale2026-misura1.3.1-uni-afam#217]
Buongiorno,
segnalo un'anomalia in fase di generazione delle classi Java utilizzando il plugin: OpenApi Generator Maven Plugin per l'operazione IFS02.3.
All'interno della response ProofEducationCourses non viene generata una lista per l'oggetto ProofEducationCourse, bensì un oggetto semplice.
Modificando il file yaml come segue (utilizzando la stessa sintassi presente IFS01.1 che è simile in quanto restituisce una lista) :
```
proof_education_courses:
  additionalProperties: false
  type: object
  description: Examinations details of student / Dettaglio esami di una studentessa o di uno studente
  properties:
    personal_data:
      $ref: '#/components/schemas/personal_data'
    proof_education_course:
      type: array
      items:
        $ref: '#/components/schemas/proof_education_course'
```

la lista viene generata correttamente.
Potete verificare per favore? 
Grazie mille

**Comment by denismarini** [comment]
Grazie per la segnalazione @s-cenni, ci lavoriamo per adeguarlo e ti facciamo sapere

**Comment by davidelongo-ey** [comment]
Salve @s-cenni ,

ci risulta che **proof_education_course** sia già definito come array su IFS2.3
Abbiamo tuttavia aggiunto la proprietà maxItems al fine di definire la struttura in modo esaustivo.

La modifica dello yaml è presente al seguente path (branch DEV): https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/dev/src/IFS02-iscrizioni.yaml


Di seguito un "estratto" dell'intervento: 

```
    proof_education_courses:
      additionalProperties: false
      type: object
      description: Examinations details of student / Dettaglio esami di una studentessa o di uno studente
      properties:
        personal_data:
          $ref: '#/components/schemas/personal_data'
        proof_education_course:
          type: array
          minItems: 0
          maxItems: 256    **<-- Attributo aggiunto**
          items:
            $ref: '#/components/schemas/proof_education_course'
```

**Potrebbe riprovare?** 
Ci faccia sapere se ora è tutto ok 
Saluti
