### ISSUE TITLE
IFS06 dubbio impronte

### ISSUE THREAD

**Issue by silviaavella** [italia/api-padigitale2026-misura1.3.1-uni-afam#219]
Buongiorno, abbiamo un dubbio sulle impronte da restituire per l'IFS.
nel caso di uno studente con più iscrizioni (ad esempio una con anno 2021/2022 e una con anno accademico 2023/2024) doppio restituire:

key: corrisponde al codice fiscale dello studente
hash: è l'impronta di ogni iscrizione (una 2021/2022 e una 2023/2024)

"enrollments_hash": [
      {
        "key": "8e44f796d7478a135c226598939d56a5b0d9405210235d4845ed158a7fec7535", 
        "hash": "56c3880bfcc4df0e35780c805d9ec942bbb8b4e237c1b63c6f2688cb58ef0a3a"
      },
      {
        "key": "8e44f796d7478a135c226598939d56a5b0d9405210235d4845ed158a7fec7535",
        "hash": "df8340f834tr8f3j84fj48jf83fngooero45305jf30l04k0r43kfd043kdew34t"
      }
    ]

oppure
key: corrisponde al codice fiscale dello studente
hash: è l'impronta di tutte e due le iscrizione

"enrollments_hash": [
      {
        "key": "8e44f796d7478a135c226598939d56a5b0d9405210235d4845ed158a7fec7535", 
        "hash": "56c3880bfcc4df0e35780c805d9ec942bbb8b4e237c1b63c6f2688cb58ef0a3a"
      }
    ]

Vi ringrazio in anticipo, saluti

**Comment by denismarini** [comment]
Buonasera Silvia,

La tua seconda proposta è quella corretta: l’impronta si riferisce all’intera posizione delle iscrizioni dello studente. Se la firma dovesse cambiare, il fruitore richiederà tutti i dati relativi alla posizione complessiva dello studente, che in questo caso comprende entrambe le iscrizioni. In altre parole, la firma copre l’intera situazione iscrittiva dello studente. Lo stesso principio si applica anche alle qualifiche.

Grazie
