### ISSUE TITLE
Errori formali su file yaml relativi alle IFS04 e IFS05 

### ISSUE THREAD

**Issue by francescosangiovanni** [italia/api-padigitale2026-misura1.3.1-uni-afam#220]
Buongiorno,
abbiamo riscontrato alcuni problemi nell'utilizzo delle classi java autogenerate dai file yaml delle IFS04 e IFS05.
Localmente li abbiamo modificati in questo modo:

IFS04 - data_request: rimossi "format: date", "minLength: 1", "maxLength: 36" - aggiunti "nullable: true" e "pattern: '^\d{4}-\d{2}-\d{2}$'"
IFS04 - birth_date: rimosso "format: date"

IFS05 - data_request: rimossi "format: date", "minLength: 1", "maxLength: 36" - aggiunti "nullable: true" e "pattern: '^\d{4}-\d{2}-\d{2}$'"
IFS05 - birth_date: rimosso "format: date"
IFS05 - academic_qualification_date: rimosso "format: date", aggiunto "nullable: true"

E' possibile una modifica anche ai file yaml del repository?

Grazie

**Comment by denismarini** [comment]
Buonasera @francescosangiovanni,

Abbiamo rimosso i valori min e max per tutte le date, in quanto si trattava di un refuso. Potreste verificare che il plug-in Java funzioni correttamente? Inoltre, se avete ulteriori suggerimenti per migliorare lo YAML, mantenendo però il formato attuale delle date, vi invitiamo a condividerli.

Se non riusciamo a trovare una soluzione, per quanto riguarda la generazione della stub in Java, è possibile apportare le modifiche che avete già effettuato. Tuttavia, vi ricordo di **pubblicare su PDND esattamente lo YAML aggiornato su questo repository.**

In attesa di un tuo riscontro
