### ISSUE TITLE
Errori formali per i tipi enumerativi su IFS04 e IFS05

### ISSUE THREAD

**Issue by francescosangiovanni** [italia/api-padigitale2026-misura1.3.1-uni-afam#221]
Buongiorno,
per i tipi enumerativi presenti nelle IFS04 e IFS05 abbiamo rimosso le proprietà minLength e maxLength.
E' possibile rimuoverli?

Grazie
Ciao

**Comment by denismarini** [comment]
Buonasera @francescosangiovanni,

Abbiamo risolto come indicato,

Grazie
