### ISSUE TITLE
attributi nullable

### ISSUE THREAD

**Issue by isidata23** [italia/api-padigitale2026-misura1.3.1-uni-afam#223]
Buongiorno
Ci sono degli attributi ai quali per forza di cose non possiamo assegnare un valore in quanto non presente per una determinata Istituzione, ad esempio per learning_ref dello schema learnings, che però è sprovvisto dell'attributo nullable, pertanto la validazione Open api 3.0 non andrebbe a buon fine.

https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS01-offerta-formativa.yaml

Grazie

**Comment by denismarini** [comment]
Buongiorno @isidata23,

Grazie per la segnalazione, abbiamo reso learning_ref nullable, ricordo anche che se un attributo non è required può essere anche completamente omesso nella risposta,

Saluti,

Denis
