### ISSUE TITLE
Oggetto: IFS04.1 attribute_name obbligatorio

### ISSUE THREAD

**Issue by silviaavella** [italia/api-padigitale2026-misura1.3.1-uni-afam#224]
Buongiorno,
nello schema della request IFS04.1, l'attributo "attribute_name" dichiarato obbligatorio è stato definito nullable: true.
Riteniamo che sia un refuso; una richiesta di correzione che non riporta l'attributo da correggere è inapplicabile. In tal caso, possiamo prevedere  una response "400 - Bad Request"?

vi ringraziamo in anticipo

Team Sapienza

**Comment by denismarini** [comment]
Buonasera,

Abbiamo apportato la correzione da voi proposta

Mille grazie

**Comment by silviaavella** [comment]
Buongiorno, grazie mille. Potremmo apportare la stessa correzione anche  per l'ifs05.1?

grazie

**Comment by denismarini** [comment]
Buongiorno,

Correzione eseguita,

Saluti,

Denis Marini
Presidenza del Consiglio dei Ministri

[Logo DTD]

innovazione.gov.it<https://innovazione.gov.it/>
[Logo Facebook]<https://www.facebook.com/DipartimentoTrasformazioneDigitale/> [Logo Twitter] <https://twitter.com/InnovazioneGov>  [Logo LinkedIn] <https://www.linkedin.com/company/dipartimentotrasformazionedigitale/>
________________________________
Da: silviaavella ***@***.***>
Inviato: martedì 8 ottobre 2024 10:03
A: italia/api-padigitale2026-misura1.3.1-uni-afam ***@***.***>
Cc: Marini Denis ***@***.***>; State change ***@***.***>
Oggetto: Re: [italia/api-padigitale2026-misura1.3.1-uni-afam] Oggetto: IFS04.1 attribute_name obbligatorio (Issue #224)


Buongiorno, grazie mille. Potremmo apportare la stessa correzione anche per l'ifs05.1?

grazie
