### ISSUE TITLE
Oggetto: Valorizzazione campi opzionali IFS04.4 e IFS05.4

### ISSUE THREAD

**Issue by silviaavella** [italia/api-padigitale2026-misura1.3.1-uni-afam#225]
Buongiorno,
nello schema della request IFS04.4 e IFS05.4, gli attributi "subscriber_id", "subscriber_name" e "subscriber_message" sono dichiarati opzionali ma vorremmo renderli obbligatori, e non accettare la richiesta in loro assenza. E' possibile?non riteniamo corretto accogliere richieste di segnalazioni senza un richiedente esplicitato.

Grazie in anticipo, saluti
Team Sapienza

**Comment by denismarini** [comment]
Buonasera,

Abbiamo ritenuto di metterli obbligatori come da voi proposto.  

Mille grazie
