### ISSUE TITLE
Verifica validità yaml non superata (IFS02, IFS03, IFS04,...)

### ISSUE THREAD

**Issue by lrollandi** [italia/api-padigitale2026-misura1.3.1-uni-afam#226]
Gentilissimi,
in interfaccia PDND viene richiesto di effettuare la validazione dello yaml caricato con:
https://italia.github.io/api-oas-checker/

Stiamo però verificando errori di validazione del src pubblicato qui su github per IFS02, IFS03, IFS04,.. (non ho proseguito con verifiche sui successivi). 

Come ci dobbiamo comportare per proseguire con pubblicazione in test di yaml validi?

Grazie
Buona serata
Loredana Rollandi

**Comment by denismarini** [comment]
Buonasera @lrollandi,

Si tratta di uno degli errori del checker che stiamo correggendo, di seguito i 2 **errori da ignorare:**

- errore dovuto alla seguente **regex ^[\p{L}'\- ]+$ .**: errore indicato dal checker **`example` property should match pattern `^[\p{L}`’\- ]+$`**
- Le enum dichiarate nullable producono un errore sugli gli esempi come nel seguente [yaml](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS04-rettifica-iscrizioni.yaml): errore indicato dal checker **`file_status` property should be equal to one of the allowed values: `approved`, `rejected`, `acquired`, `cancelled`**

Per quanto riguarda il versionamento, l’indicazione è di seguire il branch “main”, che contiene la **Release Candidate della versione 2.0.6**. Le modifiche vengono apportate sul branch “dev” e successivamente integrate nel “main”. Al momento, le segnalazioni sono diminuite e prevediamo di rilasciare la versione finale 2.0.6 entro la fine di ottobre. **Raccomandiamo di pubblicare in produzione su PDND esattamente i file YAML della release 2.0.6 che sarà rilasciata sul GitHub del DTD, ad eccezione delle intestazioni specifiche dell’istituto e gli url dei server**

Grazie per la segnalazione.
