### ISSUE TITLE
OperationId di IFS03.1 in Italiano

### ISSUE THREAD

**Issue by s-cenni** [italia/api-padigitale2026-misura1.3.1-uni-afam#227]
Segnalo che nello yaml per IFS03.01 l'operationId è, al contrario degli altri, in italiano 
https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/src/IFS03-titoli.yaml#L128

**Comment by denismarini** [comment]
Buonasera @s-cenni,

Ho eseguito la stessa correzione anche sulla IFS08 e IFS09,

Mille grazie
