### ISSUE TITLE
4.4 request parameter birth place

### ISSUE THREAD

**Issue by isidata23** [italia/api-padigitale2026-misura1.3.1-uni-afam#228]
![Cattura](https://github.com/user-attachments/assets/1ae2f132-b2aa-4dbe-a4c5-a98db7a02e0b)

Buonasera,
Viene indicato che il parametro della request birth_place debba prevedere la forma *<nome_nazione>,<codice_provincia>,<nome_comune>, *.
C'è infatti anche la RegEx da applicare, ma la dicitura "Dove possibile" mi fa venire il dubbio:  qualora il parametro non rispecchi la regola, posso comunque procedere all'acquisizione della richiesta o ritorno un 200 ok con file_status "rejected"

Gentilissimi, grazie mille

Fabio Fonzo, ISIDATA

**Comment by denismarini** [comment]
Buongiorno Fabio,

Nome, Cognome, Data di Nascita e Luogo di Nascita devono essere forniti solo in assenza del Codice Fiscale. In tal caso, il Luogo di Nascita diventa obbligatorio e deve essere validato secondo le regole specificate e la RegEx fornita. Se il Luogo di Nascita non rispetta la RegEx, il sistema deve restituire uno stato “rejected”. Tuttavia, se il sistema è in grado di gestire formati che non rispettano pienamente la RegEx, è possibile accettarli e restituire uno stato 200, gestendo correttamente il dato.

Spero di essere stato chiaro,

Grazie a te

**Comment by isidata23** [comment]
Chiarissimo, grazie!
Fabio

ISIDATA
