### ISSUE TITLE
Nomenclatura corretta PA digitale 2026

### ISSUE THREAD

**Issue by gianvitofanelli** [italia/api-padigitale2026-misura1.3.1-uni-afam#229]
Ciao, ho notato che la nomenclatura nel readme non è quella corretta; dovrebbe essere "PA digitale 2026".

Grazie!

**Comment by denismarini** [comment]
Ciao @gianvitofanelli,

E' stata corretta la nomenclatura su dev e main,

Mille grazie per la segnalazione
