### ISSUE TITLE
pattern given_name, family_name nelle IFS02, IFS03, IFS04, IFS05

### ISSUE THREAD

**Issue by francescosangiovanni** [italia/api-padigitale2026-misura1.3.1-uni-afam#231]
Buongiorno,
come da aggetto i pattern attuali dei campi given_name, family_name delle IFS02, IFS03, IFS04, IFS05 non passano il check del validatore https://italia.github.io/api-oas-checker/.

Il pattern corretto deve essere ^[p{L}} ,.'-’\s''-Ӑ]+$.

Grazie
Saluti

**Comment by denismarini** [comment]
Buongiorno @francescosangiovanni,

La invito a consultare la issue #226. Abbiamo risolto il problema relativo all'enum nel file_status nell’ambito della community per la specifica OpenAPI. Tuttavia, il problema relativo alla validazione della regex è legato all'implementazione del checker da terze parti e non è ancora stato risolto, pertanto l’errore sul checker può essere ignorato per il momento.

Grazie per la segnalazione
