### ISSUE TITLE
Hash delle iscrizioni

### ISSUE THREAD

**Issue by s-cenni** [italia/api-padigitale2026-misura1.3.1-uni-afam#234]
Buongiorno,
per IFS06 abbiamo i seguenti dubbi:

1. HASH (Iscrizione) è generato dall’array enrollments nel json (come da risposta alla issue: https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/issues/219) oppure per l’intero oggetto json (comprensivo di personal data)? 
2. Nella response ifs06 operation 1 il valore “last_update” come deve essere valorizzato? Deve essere la data dell’ultima iscrizione modificata oppure la data in cui ha girato per l'ultima volta il job di aggiornamento?
3. Nella response dell’[immagine](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/raw/main/doc/05_gallery/ifs06-ANIS%20update%20process.drawio.png) i dati restituiti sono diversi da quelli della response [file yaml ](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/03_analysis/io_schema/IFS02.1-response.json) (in particolare manca il campo Institute name). E' corretto?

**Comment by denismarini** [comment]
Buonasera @s-cenni,

> Buongiorno, per IFS06 abbiamo i seguenti dubbi:
> 
> 1. HASH (Iscrizione) è generato dall’array enrollments nel json (come da risposta alla issue: [IFS06 dubbio impronte #219](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/issues/219)) oppure per l’intero oggetto json (comprensivo di personal data)?

**Consiglio per l'intera posizione, quindi inclusa il personal data**

> 2. Nella response ifs06 operation 1 il valore “last_update” come deve essere valorizzato? Deve essere la data dell’ultima iscrizione modificata oppure la data in cui ha girato per l'ultima volta il job di aggiornamento?

**Data in cui ha girato per l'ultima volta il job di aggiornamento**

> 3. Nella response dell’[immagine](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/raw/main/doc/05_gallery/ifs06-ANIS%20update%20process.drawio.png) i dati restituiti sono diversi da quelli della response [file yaml ](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/main/doc/03_analysis/io_schema/IFS02.1-response.json) (in particolare manca il campo Institute name). E' corretto?

**E' corretto, l'immagine non è stata aggiornata, ha lo scopo solo di fornire un'idea della mimica d'interazione, nei dettagli fa fede la definizione openAPI**
