### ISSUE TITLE
Errori di validazione yaml IFS02, IFS03, IFS04, IFS05

### ISSUE THREAD

**Issue by lrollandi** [italia/api-padigitale2026-misura1.3.1-uni-afam#235]
Gentilissimi,
ho controllato gli yaml aggiornati all'ultima release (updated version 2.1.0 https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/tree/main/src ) ma ancora rilevo errori di validazione per gli yaml in oggetto con https://italia.github.io/api-oas-checker/ (13 errori per IFS02 e IFS03 e 4 errori per IFS04 e IFS05).
Potete gentilmente farmi sapere come procedere per renderli validi?

Grazie in anticipo
Buona giornata
Saluti
Loredana Rollandi

**Comment by denismarini** [comment]
Buongiorno Loredana,

L’errore mostrato nell’immagine sotto è legato allo strumento OpenAPI e non alla correttezza della specifica OpenAPI. Pertanto, può tranquillamente ignorarlo. Per maggiori dettagli, può consultare la issue #231.

Le raccomando di pubblicare in produzione sulla PDND esattamente la specifica da noi fornita, personalizzando unicamente le informazioni relative all'Istituto e all’endpoint del server.

Saluti, 

 
<img width="468" alt="image" src="https://github.com/user-attachments/assets/9ddcb87c-71e4-4dda-a840-d421adb9d41f">
