### ISSUE TITLE
API unica per le rettifiche

### ISSUE THREAD

**Issue by rockmesh** [italia/api-padigitale2026-misura1.3.1-uni-afam#3]
Le API [rettifica-anagrafica-studente-new.ya](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/next/rettifica-anagrafica-studente-new.yaml) e [stato-rettifiche-studente.yaml](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/blob/next/stato-rettifiche-studente.yaml) dovrebbero essere una unica API con più endpoint.

**Comment by AulicinoDiego** [comment]
mergiate in una unica API come richiesto
