### ISSUE TITLE
Chiarimenti sui tracciati 

### ISSUE THREAD

**Issue by NETTunoPA** [italia/api-padigitale2026-misura1.3.1-uni-afam#52]
Buongiorno,
stiamo sviluppando le api per gli AFAM in riferimento alla misura 1.3.1 PDND. Vorremmo sapere se al fine della validazione è necessario attenersi ai tracciati  che avete pubblicato in questo repository o se il tracciato può essere differente (saranno chiaramente caricate le specifiche delle api al momento della profilazione dell'e-service).
Grazie e buona giornata

**Comment by denismarini** [comment]
Buongiorno,

Scusa il ritardo nella risposta!
Se con tracciati si indica le specifiche Open API, ossia gli yaml nella cartella src è necessario rimanere attinenti a questa specifica nell'implementazione. Consiglio di guardare il branch dev per ottenere la situazione sempre più aggiornate. Al termine della definizione delle API faremo un altro tag stabile. Le API sono in chiusura e stiamo aggiornando anche il README.MD
