### ISSUE TITLE
Studenti iscritti

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#7]
studenti-iscritti-ifm io toglierei il postfisso ifm ed inoltre aggiungerei un filtro anno come aveva indicato Rocco nel documento di analisi

**Comment by denismarini** [comment]
Provo a fare direttamente la proposta nella pull request che stiamo preparando

**Comment by AulicinoDiego** [comment]
potreste spiegarmi meglio la richiesta dei commenti precedenti così da poterla prendere in carico? Inoltre c'è per caso una nuova versione del documento di analisi (io ho il documento API Università rev 1.0) ?

**Comment by denismarini** [comment]
Ciao @AulicinoDiego scusami ma vedo il tuo messaggio solo ora, hai risolto già con @mfortini ?

**Comment by AulicinoDiego** [comment]
Ciao, nel frattempo è cambiato il documento delle API quindi forse questa issue può essere chiusa
