### ISSUE TITLE
Verifica formato person_id

### ISSUE THREAD

**Issue by ASM75** [italia/api-padigitale2026-misura1.3.1-uni-afam#75]
In relazione alla _regex_ associata al **person_id** definite in **IFS03_Titoli.yaml** e **IFS02_Iscrizioni.yaml** segnalo che non consente di validare tutti i possibli valori di ID ANPR, invece di 
  ^[A-Z0-9]{8}[A-Z]$
propongo di usare la regola
  ^[A-Z0-9]{9}$

**Comment by denismarini** [comment]
@davidelongo-ey @ldoneda dovremmo rivedere con https://www.anagrafenazionale.interno.it/anpr/notizie/identificativo-unico-nazionale-idanpr/

**Comment by davidelongo-ey** [comment]
ok, procediamo con la modifica in  ^[A-Z0-9]{9}$

**Comment by davidelongo-ey** [comment]
La modifica è già stata eseguita diverse settimane fa. Chiudo
