### ISSUE TITLE
IFS02 non valido

### ISSUE THREAD

**Issue by fabio2602** [italia/api-padigitale2026-misura1.3.1-uni-afam#76]
sullo yaml vi sono 3 errori tutti legati alla probabile inversione del valore min e max dell'institute code

name: institute_code
          in: query
          required: false
          schema:
            type: string
            maxLength: 1
            minLength: 32
            description: Institute code / Codice istituto

**Comment by davidelongo-ey** [comment]
Ciao Fabio, 
grazie della segnalazione e scusa il ritardo della nostra risposta.
La issue è stata risolta settimane fa.

A presto
