### ISSUE TITLE
attributo status negli enrollment senza restriction

### ISSUE THREAD

**Issue by fabio2602** [italia/api-padigitale2026-misura1.3.1-uni-afam#95]
l'attributo status presente nella struttura di enrollment dovrebbe avere una restriction basata su enumeration, in maniera da vincolarne i valori ad almeno 3 stati: attivo, non attivo, sospeso

**Comment by davidelongo-ey** [comment]
Ciao Fabio,

l'aggiunta dell' Enum sull'attributo **status** è stata pushata sul branch DEV

Grazie della segnalazione
