### ISSUE TITLE
Linee Guida, riportare i nomi come pubblicare le API su PDND

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#96]

**Comment by davidelongo-ey** [comment]
Denis non ho capito bene
Il nome dell'e-service l'abbiamo gia inserito nel readme

![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139359776/7527f075-f017-43f5-a481-c0d83a862357)

**Comment by denismarini** [comment]
Aggiungere una sezione "Importante:" sul readme.md prima dell'inizio del capitolo "linee guida" nel qual si pone in evidenza di pubblicare le API con i nomi indicati nella tabella 1 colona "e-service": 

Si ricorda che in fase di pubblicazione degli e-service il nome deve corrispondere a quello della colonna "e-service" nella tabella 1

**Comment by davidelongo-ey** [comment]
![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139359776/a923c28c-93cf-48ca-812d-a9f00ed37334)

**Comment by denismarini** [comment]
Verificato, la chiudo
