### ISSUE TITLE
Iscrizioni - IFS02.1 - Linee guida parametri opzionali

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#97]

**Comment by denismarini** [comment]
Per IFS02.1

regole di obbligatorietà:

**personal_data:** tax_code and/or person_id or (given_name, family_name, birth_date, birth_place)

Esempio 1:

```
"personal_data": {
    "tax_code": "RSSMRA80A01F205D"
  }
```
Esempio 2:
```
"personal_data": {
    "tax_code": "RSSMRA80A01F205D",
    "person_id": "AB123456C"
  }
```
Esempio 3
```
"personal_data": {
    "given_name": Mario,
    "family_name": Rossi,
    "birth_date": 10-01-2022,
    "birth_place": Roma
  }
```

**enrollments:**  di seguito l'obbligatorietà con "*"

```
  "enrollments": [
    {
      "institute_code": "16",  *
      "institute_name": "Milano - Politecnico", *
      "programme_type_code": "MS", *
      "degree_course_code": "1573960", *
      "degree_class_code": "LM-32",
      "academic_year": "2021/2022", *
      "degree_course_year": 3, *
      "status": "attivo" *
    }
  ]
```
Se almeno uno degli attributi obbligatori ** NON ** è valorizzabile non si restituisce l'istanza dell'iscrizione. Quindi, il degree_class_code può assumere il valore null.

**Comment by davidelongo-ey** [comment]
vedi mio commento issue https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/issues/105

**Comment by denismarini** [comment]
@davidelongo-ey  ho aggiornato la #105 e conservo questa issue per fare la revisione delle Linee guida assegnandola a me in stato di "in stage"

**Comment by denismarini** [comment]
Aggiornata e verificata, la chiudo
