### ISSUE TITLE
Titoli - IFS03.1 - parametri opzionali

### ISSUE THREAD

**Issue by denismarini** [italia/api-padigitale2026-misura1.3.1-uni-afam#98]
Per IFS02.1

regole di obbligatorietà:

**personal_data:** tax_code and/or person_id or (given_name, family_name, birth_date, birth_place)

Esempio 1:

```
"personal_data": {
    "tax_code": "RSSMRA80A01F205D"
  }
```
Esempio 2:
```
"personal_data": {
    "tax_code": "RSSMRA80A01F205D",
    "person_id": "AB123456C"
  }
```
Esempio 3
```
"personal_data": {
    "given_name": Mario,
    "family_name": Rossi,
    "birth_date": 10-01-2022,
    "birth_place": Roma
  }
```

**qualifications:**  di seguito l'obbligatorietà con "*"

```
Esempi 1:
"qualifications": [
    {
      "institute_code": "16", *
      "institute_name": "Milano - Politecnico", *
      "qualification_name": "Dottore magistrale", *
      "programme_type_code": "MS", *
      "degree_course_code": "1573960", *
      "degree_class_code": "LM-32",
      "academic_qualification_date": "2022-07-01", *
      "qualification_grade_value": "110", 
      "qualification_grading_scale": "110", 
      "qualification_grading_scale_minimum_grade": null,
      "qualification_grading_scale_maximum_grade": "null"
    }
  ]

Esempio 2:
"qualifications": [
    {
      "institute_code": "16", *
      "institute_name": "Milano - Politecnico", *
      "qualification_name": "Idoneità di inglese", *
      "programme_type_code": "MS", *
      "degree_course_code": "1573960", *
      "degree_class_code": null,
      "academic_qualification_date": "2022-07-01", *
      "qualification_grade_value": "Idoneo", 
      "qualification_grading_scale": null, 
      "qualification_grading_scale_minimum_grade": null,
      "qualification_grading_scale_maximum_grade": "null"
    }
  ]
```
Se almeno uno degli attributi obbligatori **NON** è valorizzabile non si restituisce l'istanza del titolo. Gli attributi non obbligatori possono assumere valori "null"

**Comment by davidelongo-ey** [comment]
Fatto, commitato nel branch dev

**Comment by denismarini** [comment]
@davidelongo-ey questa non la possiamo chiudere, di seguito i motivi:

- [ ] Da rivedere i parametri d'ingresso come per IFS02.1 perché l'esempio non è reale
- [ ] Eliminare l'obbligatorietà dei parametri d'ingresso e descrivere bene sulle linee guida
- [ ] L'obbligatorietà della risposta deve essere sul singolo attributo e non sugli oggetti personal_data e qualifcations*



![Image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/f4f6262f-461d-4268-888f-5185a13116e4)

**Comment by davidelongo-ey** [comment]
per il punto 3 intendi così? (vedi esempio sotto)
![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139359776/7adbf57a-1e54-48a8-848d-bcc739548822)

**Comment by denismarini** [comment]
Intendo così ma il degree_class_code non è obbligatorio

**Comment by davidelongo-ey** [comment]
Già risolto qualche giorno fa

![image](https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/139359776/a59ec08e-b841-4b34-a446-810760d8bb17)

**Comment by denismarini** [comment]
Qui parliamo dei titoli non delle iscrizioni, il titolo contiene IFS03

<img width="670" alt="image" src="https://github.com/italia/api-padigitale2026-misura1.3.1-uni-afam/assets/8019448/02aff504-752c-4c98-b0ba-b6a498b853a3">
