### ISSUE TITLE
Formato last_update non coerente su eservices IFS06.1 e IFS07.1 (tag 1.1.0)

### ISSUE THREAD

**Issue by fabio2602** [italia/api-padigitale2026-misura1.3.1-uni-afam#99]
Il formato dell'attributo last_update su eservices IFS06.1 e IFS07.1 non è coerente: talvolta viene proposto solo data ed altre volte come data-ora.
Suggerisco di impostarlo come data con vincolo: pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'

**Comment by davidelongo-ey** [comment]
modificati yaml ifs06 e ifs07.
i json erano correttamente formattati
